package Secciones;

import javax.swing.ImageIcon;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author aarui
 */
public class NueveUno extends javax.swing.JFrame {

    /**
     * Creates new form NueveUno
     */
    public NueveUno() {
        initComponents();
        setLocationRelativeTo(null);
        ImageIcon ii;
        ii=new ImageIcon(this.getClass().getResource("/Imagenes/HORARIO.png"));
        this.setIconImage(ii.getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Lunes = new javax.swing.JLabel();
        Lunes1 = new javax.swing.JLabel();
        Lunes2 = new javax.swing.JLabel();
        Lunes3 = new javax.swing.JLabel();
        Lunes4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextArea6 = new javax.swing.JTextArea();
        jTextArea2 = new javax.swing.JTextArea();
        jTextArea3 = new javax.swing.JTextArea();
        jTextArea4 = new javax.swing.JTextArea();
        jTextArea7 = new javax.swing.JTextArea();
        jTextArea8 = new javax.swing.JTextArea();
        jTextArea9 = new javax.swing.JTextArea();
        jTextArea18 = new javax.swing.JTextArea();
        jTextArea19 = new javax.swing.JTextArea();
        jTextArea20 = new javax.swing.JTextArea();
        jTextArea21 = new javax.swing.JTextArea();
        jTextArea22 = new javax.swing.JTextArea();
        jTextArea24 = new javax.swing.JTextArea();
        jTextArea25 = new javax.swing.JTextArea();
        jTextArea26 = new javax.swing.JTextArea();
        jTextArea27 = new javax.swing.JTextArea();
        jTextArea28 = new javax.swing.JTextArea();
        jTextArea30 = new javax.swing.JTextArea();
        jTextArea31 = new javax.swing.JTextArea();
        jTextArea32 = new javax.swing.JTextArea();
        jTextArea33 = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jTextArea34 = new javax.swing.JTextArea();
        jTextArea35 = new javax.swing.JTextArea();
        jTextArea23 = new javax.swing.JTextArea();
        jTextArea29 = new javax.swing.JTextArea();
        jTextArea36 = new javax.swing.JTextArea();
        jTextArea37 = new javax.swing.JTextArea();
        jTextArea38 = new javax.swing.JTextArea();
        jTextArea39 = new javax.swing.JTextArea();
        jTextArea13 = new javax.swing.JTextArea();
        jTextArea14 = new javax.swing.JTextArea();
        jTextArea15 = new javax.swing.JTextArea();
        jTextArea10 = new javax.swing.JTextArea();
        jTextArea11 = new javax.swing.JTextArea();
        jTextArea12 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setLayout(null);

        Lunes.setBackground(new java.awt.Color(153, 204, 255));
        Lunes.setText("Martes");
        Lunes.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Lunes.setInheritsPopupMenu(false);
        Lunes.setOpaque(true);
        jPanel1.add(Lunes);
        Lunes.setBounds(210, 10, 100, 20);

        Lunes1.setBackground(new java.awt.Color(153, 204, 255));
        Lunes1.setText("Viernes");
        Lunes1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Lunes1.setInheritsPopupMenu(false);
        Lunes1.setOpaque(true);
        jPanel1.add(Lunes1);
        Lunes1.setBounds(510, 10, 100, 20);

        Lunes2.setBackground(new java.awt.Color(153, 204, 255));
        Lunes2.setText("Jueves");
        Lunes2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Lunes2.setInheritsPopupMenu(false);
        Lunes2.setOpaque(true);
        jPanel1.add(Lunes2);
        Lunes2.setBounds(410, 10, 100, 20);

        Lunes3.setBackground(new java.awt.Color(153, 204, 255));
        Lunes3.setText("Miercoles");
        Lunes3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Lunes3.setInheritsPopupMenu(false);
        Lunes3.setOpaque(true);
        jPanel1.add(Lunes3);
        Lunes3.setBounds(310, 10, 100, 20);

        Lunes4.setBackground(new java.awt.Color(153, 204, 255));
        Lunes4.setText("Lunes");
        Lunes4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Lunes4.setInheritsPopupMenu(false);
        Lunes4.setOpaque(true);
        jPanel1.add(Lunes4);
        Lunes4.setBounds(110, 10, 100, 20);

        jLabel5.setBackground(new java.awt.Color(102, 153, 255));
        jLabel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLabel5.setOpaque(true);
        jPanel1.add(jLabel5);
        jLabel5.setBounds(110, 340, 500, 30);

        jLabel6.setBackground(new java.awt.Color(102, 153, 255));
        jLabel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLabel6.setOpaque(true);
        jPanel1.add(jLabel6);
        jLabel6.setBounds(110, 230, 500, 30);

        jLabel7.setBackground(new java.awt.Color(102, 153, 255));
        jLabel7.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLabel7.setOpaque(true);
        jPanel1.add(jLabel7);
        jLabel7.setBounds(110, 120, 500, 30);

        jTextArea6.setEditable(false);
        jTextArea6.setBackground(new java.awt.Color(153, 255, 255));
        jTextArea6.setColumns(20);
        jTextArea6.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jTextArea6.setRows(5);
        jTextArea6.setText("Libre\n");
        jTextArea6.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextArea6.setMinimumSize(new java.awt.Dimension(60, 11));
        jPanel1.add(jTextArea6);
        jTextArea6.setBounds(510, 430, 100, 20);

        jTextArea2.setEditable(false);
        jTextArea2.setBackground(new java.awt.Color(153, 255, 255));
        jTextArea2.setColumns(20);
        jTextArea2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jTextArea2.setRows(5);
        jTextArea2.setText("Informática\nEducativa");
        jTextArea2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jTextArea2);
        jTextArea2.setBounds(210, 260, 100, 50);

        jTextArea3.setEditable(false);
        jTextArea3.setBackground(new java.awt.Color(153, 255, 255));
        jTextArea3.setColumns(20);
        jTextArea3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jTextArea3.setRows(5);
        jTextArea3.setText("Matemáticas");
        jTextArea3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jTextArea3);
        jTextArea3.setBounds(210, 150, 100, 80);

        jTextArea4.setEditable(false);
        jTextArea4.setBackground(new java.awt.Color(153, 255, 255));
        jTextArea4.setColumns(20);
        jTextArea4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jTextArea4.setRows(5);
        jTextArea4.setText("Educ.Física");
        jTextArea4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jTextArea4);
        jTextArea4.setBounds(210, 370, 100, 30);

        jTextArea7.setEditable(false);
        jTextArea7.setBackground(new java.awt.Color(153, 255, 255));
        jTextArea7.setColumns(20);
        jTextArea7.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jTextArea7.setRows(5);
        jTextArea7.setText("Español");
        jTextArea7.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jTextArea7);
        jTextArea7.setBounds(310, 260, 100, 80);

        jTextArea8.setEditable(false);
        jTextArea8.setBackground(new java.awt.Color(153, 255, 255));
        jTextArea8.setColumns(20);
        jTextArea8.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jTextArea8.setRows(5);
        jTextArea8.setText("Herramientas\nde progra-B");
        jTextArea8.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextArea8.setMinimumSize(new java.awt.Dimension(60, 11));
        jPanel1.add(jTextArea8);
        jTextArea8.setBounds(110, 410, 100, 40);

        jTextArea9.setEditable(false);
        jTextArea9.setBackground(new java.awt.Color(153, 255, 255));
        jTextArea9.setColumns(20);
        jTextArea9.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jTextArea9.setRows(5);
        jTextArea9.setText("Conociendo \nlos negocios-A");
        jTextArea9.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextArea9.setMinimumSize(new java.awt.Dimension(60, 11));
        jPanel1.add(jTextArea9);
        jTextArea9.setBounds(110, 370, 100, 40);

        jTextArea18.setEditable(false);
        jTextArea18.setBackground(new java.awt.Color(153, 255, 255));
        jTextArea18.setColumns(20);
        jTextArea18.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jTextArea18.setRows(5);
        jTextArea18.setText("Frances");
        jTextArea18.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jTextArea18);
        jTextArea18.setBounds(210, 40, 100, 80);

        jTextArea19.setEditable(false);
        jTextArea19.setBackground(new java.awt.Color(153, 255, 255));
        jTextArea19.setColumns(20);
        jTextArea19.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jTextArea19.setRows(5);
        jTextArea19.setText("Ciencias");
        jTextArea19.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jTextArea19);
        jTextArea19.setBounds(510, 260, 100, 80);

        jTextArea20.setEditable(false);
        jTextArea20.setBackground(new java.awt.Color(153, 255, 255));
        jTextArea20.setColumns(20);
        jTextArea20.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jTextArea20.setRows(5);
        jTextArea20.setText("Inglés");
        jTextArea20.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jTextArea20);
        jTextArea20.setBounds(310, 150, 100, 80);

        jTextArea21.setEditable(false);
        jTextArea21.setBackground(new java.awt.Color(153, 255, 255));
        jTextArea21.setColumns(20);
        jTextArea21.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jTextArea21.setRows(5);
        jTextArea21.setText("Español");
        jTextArea21.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jTextArea21);
        jTextArea21.setBounds(210, 400, 100, 50);

        jTextArea22.setEditable(false);
        jTextArea22.setBackground(new java.awt.Color(153, 255, 255));
        jTextArea22.setColumns(20);
        jTextArea22.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jTextArea22.setRows(5);
        jTextArea22.setText("Guía");
        jTextArea22.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jTextArea22);
        jTextArea22.setBounds(310, 90, 100, 30);

        jTextArea24.setEditable(false);
        jTextArea24.setBackground(new java.awt.Color(153, 255, 255));
        jTextArea24.setColumns(20);
        jTextArea24.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jTextArea24.setRows(5);
        jTextArea24.setText("Matemáticas");
        jTextArea24.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jTextArea24);
        jTextArea24.setBounds(410, 260, 100, 50);

        jTextArea25.setEditable(false);
        jTextArea25.setBackground(new java.awt.Color(153, 255, 255));
        jTextArea25.setColumns(20);
        jTextArea25.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jTextArea25.setRows(5);
        jTextArea25.setText("Cívica");
        jTextArea25.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jTextArea25);
        jTextArea25.setBounds(310, 40, 100, 50);

        jTextArea26.setEditable(false);
        jTextArea26.setBackground(new java.awt.Color(153, 255, 255));
        jTextArea26.setColumns(20);
        jTextArea26.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jTextArea26.setRows(5);
        jTextArea26.setText("Est.Sociales");
        jTextArea26.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jTextArea26);
        jTextArea26.setBounds(510, 370, 100, 60);

        jTextArea27.setEditable(false);
        jTextArea27.setBackground(new java.awt.Color(153, 255, 255));
        jTextArea27.setColumns(20);
        jTextArea27.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jTextArea27.setRows(5);
        jTextArea27.setText("Ciencias");
        jTextArea27.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jTextArea27);
        jTextArea27.setBounds(410, 180, 100, 50);

        jTextArea28.setEditable(false);
        jTextArea28.setBackground(new java.awt.Color(153, 255, 255));
        jTextArea28.setColumns(20);
        jTextArea28.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jTextArea28.setRows(5);
        jTextArea28.setText("Educ.Física");
        jTextArea28.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jTextArea28);
        jTextArea28.setBounds(210, 310, 100, 30);

        jTextArea30.setEditable(false);
        jTextArea30.setBackground(new java.awt.Color(153, 255, 255));
        jTextArea30.setColumns(20);
        jTextArea30.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jTextArea30.setRows(5);
        jTextArea30.setText("Fortalecimiento");
        jTextArea30.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jTextArea30);
        jTextArea30.setBounds(410, 150, 100, 30);

        jTextArea31.setEditable(false);
        jTextArea31.setBackground(new java.awt.Color(153, 255, 255));
        jTextArea31.setColumns(20);
        jTextArea31.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jTextArea31.setRows(5);
        jTextArea31.setText("Est.Sociales");
        jTextArea31.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jTextArea31);
        jTextArea31.setBounds(410, 310, 100, 30);

        jTextArea32.setEditable(false);
        jTextArea32.setBackground(new java.awt.Color(153, 255, 255));
        jTextArea32.setColumns(20);
        jTextArea32.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jTextArea32.setRows(5);
        jTextArea32.setText("Est.Sociales");
        jTextArea32.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jTextArea32);
        jTextArea32.setBounds(410, 370, 100, 30);

        jTextArea33.setEditable(false);
        jTextArea33.setBackground(new java.awt.Color(153, 255, 255));
        jTextArea33.setColumns(20);
        jTextArea33.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jTextArea33.setRows(5);
        jTextArea33.setText("Educ.Músical");
        jTextArea33.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jTextArea33);
        jTextArea33.setBounds(410, 40, 100, 50);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel8.setText("7:40 a 8:20");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(10, 70, 60, 13);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel9.setText("8:20 a 9:00");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(10, 100, 60, 13);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel10.setText("9:20 a 10:00");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(10, 150, 67, 13);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel11.setText("10:00 a 10:40");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(10, 180, 74, 13);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel12.setText("10:40 a 11:20");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(10, 210, 80, 13);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel13.setText("12:00 a 12:40");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(10, 260, 80, 13);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel14.setText("12:40 a 1:20");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(10, 290, 70, 13);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel15.setText("1:20 a 2:00");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(10, 320, 60, 13);

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel16.setText("7:00 a 7:40");
        jPanel1.add(jLabel16);
        jLabel16.setBounds(10, 40, 60, 13);

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel17.setText("2:20 a 3:00");
        jPanel1.add(jLabel17);
        jLabel17.setBounds(10, 370, 60, 13);

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel18.setText("3:00 a 3:40");
        jPanel1.add(jLabel18);
        jLabel18.setBounds(10, 400, 60, 13);

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel19.setText("3:40 a 4:20");
        jPanel1.add(jLabel19);
        jLabel19.setBounds(10, 430, 60, 13);

        jButton1.setBackground(new java.awt.Color(153, 255, 255));
        jButton1.setText("Atras");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(0, 0, 70, 24);

        jTextArea34.setEditable(false);
        jTextArea34.setBackground(new java.awt.Color(153, 255, 255));
        jTextArea34.setColumns(20);
        jTextArea34.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jTextArea34.setRows(5);
        jTextArea34.setText("Orientación");
        jTextArea34.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jTextArea34);
        jTextArea34.setBounds(410, 90, 100, 30);

        jTextArea35.setEditable(false);
        jTextArea35.setBackground(new java.awt.Color(153, 255, 255));
        jTextArea35.setColumns(20);
        jTextArea35.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jTextArea35.setRows(5);
        jTextArea35.setText("Est.Religiosa");
        jTextArea35.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jTextArea35);
        jTextArea35.setBounds(410, 400, 100, 30);

        jTextArea23.setEditable(false);
        jTextArea23.setBackground(new java.awt.Color(153, 255, 255));
        jTextArea23.setColumns(20);
        jTextArea23.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jTextArea23.setRows(5);
        jTextArea23.setText("Conociendo \nlos negocios-B");
        jTextArea23.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextArea23.setMinimumSize(new java.awt.Dimension(60, 11));
        jPanel1.add(jTextArea23);
        jTextArea23.setBounds(110, 80, 100, 40);

        jTextArea29.setEditable(false);
        jTextArea29.setBackground(new java.awt.Color(153, 255, 255));
        jTextArea29.setColumns(20);
        jTextArea29.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jTextArea29.setRows(5);
        jTextArea29.setText("Conociendo \nlos negocios-B");
        jTextArea29.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextArea29.setMinimumSize(new java.awt.Dimension(60, 11));
        jPanel1.add(jTextArea29);
        jTextArea29.setBounds(110, 190, 100, 40);

        jTextArea36.setEditable(false);
        jTextArea36.setBackground(new java.awt.Color(153, 255, 255));
        jTextArea36.setColumns(20);
        jTextArea36.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jTextArea36.setRows(5);
        jTextArea36.setText("Conociendo \nlos negocios-A");
        jTextArea36.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextArea36.setMinimumSize(new java.awt.Dimension(60, 11));
        jPanel1.add(jTextArea36);
        jTextArea36.setBounds(110, 260, 100, 40);

        jTextArea37.setEditable(false);
        jTextArea37.setBackground(new java.awt.Color(153, 255, 255));
        jTextArea37.setColumns(20);
        jTextArea37.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jTextArea37.setRows(5);
        jTextArea37.setText("Herramientas\nde progra-A");
        jTextArea37.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextArea37.setMinimumSize(new java.awt.Dimension(60, 11));
        jPanel1.add(jTextArea37);
        jTextArea37.setBounds(110, 40, 100, 40);

        jTextArea38.setEditable(false);
        jTextArea38.setBackground(new java.awt.Color(153, 255, 255));
        jTextArea38.setColumns(20);
        jTextArea38.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jTextArea38.setRows(5);
        jTextArea38.setText("Herramientas\nde progra-A");
        jTextArea38.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextArea38.setMinimumSize(new java.awt.Dimension(60, 11));
        jPanel1.add(jTextArea38);
        jTextArea38.setBounds(110, 150, 100, 40);

        jTextArea39.setEditable(false);
        jTextArea39.setBackground(new java.awt.Color(153, 255, 255));
        jTextArea39.setColumns(20);
        jTextArea39.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jTextArea39.setRows(5);
        jTextArea39.setText("Herramientas\nde progra-B");
        jTextArea39.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextArea39.setMinimumSize(new java.awt.Dimension(60, 11));
        jPanel1.add(jTextArea39);
        jTextArea39.setBounds(110, 300, 100, 40);

        jTextArea13.setEditable(false);
        jTextArea13.setBackground(new java.awt.Color(153, 255, 255));
        jTextArea13.setColumns(20);
        jTextArea13.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jTextArea13.setRows(5);
        jTextArea13.setText("Ingles\nconversacional");
        jTextArea13.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextArea13.setMinimumSize(new java.awt.Dimension(60, 11));
        jPanel1.add(jTextArea13);
        jTextArea13.setBounds(510, 40, 100, 40);

        jTextArea14.setEditable(false);
        jTextArea14.setBackground(new java.awt.Color(153, 255, 255));
        jTextArea14.setColumns(20);
        jTextArea14.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jTextArea14.setRows(5);
        jTextArea14.setText("Ingles\nconversacional");
        jTextArea14.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextArea14.setMinimumSize(new java.awt.Dimension(60, 11));
        jPanel1.add(jTextArea14);
        jTextArea14.setBounds(510, 80, 100, 40);

        jTextArea15.setEditable(false);
        jTextArea15.setBackground(new java.awt.Color(153, 255, 255));
        jTextArea15.setColumns(20);
        jTextArea15.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jTextArea15.setRows(5);
        jTextArea15.setText("Ingles\nconversacional");
        jTextArea15.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextArea15.setMinimumSize(new java.awt.Dimension(60, 11));
        jPanel1.add(jTextArea15);
        jTextArea15.setBounds(510, 150, 100, 40);

        jTextArea10.setEditable(false);
        jTextArea10.setBackground(new java.awt.Color(153, 255, 255));
        jTextArea10.setColumns(20);
        jTextArea10.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jTextArea10.setRows(5);
        jTextArea10.setText("Ingles\nconversacional");
        jTextArea10.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextArea10.setMinimumSize(new java.awt.Dimension(60, 11));
        jPanel1.add(jTextArea10);
        jTextArea10.setBounds(510, 190, 100, 40);

        jTextArea11.setEditable(false);
        jTextArea11.setBackground(new java.awt.Color(153, 255, 255));
        jTextArea11.setColumns(20);
        jTextArea11.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jTextArea11.setRows(5);
        jTextArea11.setText("Libre\n");
        jTextArea11.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextArea11.setMinimumSize(new java.awt.Dimension(60, 11));
        jPanel1.add(jTextArea11);
        jTextArea11.setBounds(310, 370, 100, 80);

        jTextArea12.setEditable(false);
        jTextArea12.setBackground(new java.awt.Color(153, 255, 255));
        jTextArea12.setColumns(20);
        jTextArea12.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jTextArea12.setRows(5);
        jTextArea12.setText("Libre\n");
        jTextArea12.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextArea12.setMinimumSize(new java.awt.Dimension(60, 11));
        jPanel1.add(jTextArea12);
        jTextArea12.setBounds(410, 430, 100, 20);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 620, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 460, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Noveno um = new Noveno();
        um.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Lunes;
    private javax.swing.JLabel Lunes1;
    private javax.swing.JLabel Lunes2;
    private javax.swing.JLabel Lunes3;
    private javax.swing.JLabel Lunes4;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextArea jTextArea10;
    private javax.swing.JTextArea jTextArea11;
    private javax.swing.JTextArea jTextArea12;
    private javax.swing.JTextArea jTextArea13;
    private javax.swing.JTextArea jTextArea14;
    private javax.swing.JTextArea jTextArea15;
    private javax.swing.JTextArea jTextArea18;
    private javax.swing.JTextArea jTextArea19;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea20;
    private javax.swing.JTextArea jTextArea21;
    private javax.swing.JTextArea jTextArea22;
    private javax.swing.JTextArea jTextArea23;
    private javax.swing.JTextArea jTextArea24;
    private javax.swing.JTextArea jTextArea25;
    private javax.swing.JTextArea jTextArea26;
    private javax.swing.JTextArea jTextArea27;
    private javax.swing.JTextArea jTextArea28;
    private javax.swing.JTextArea jTextArea29;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextArea jTextArea30;
    private javax.swing.JTextArea jTextArea31;
    private javax.swing.JTextArea jTextArea32;
    private javax.swing.JTextArea jTextArea33;
    private javax.swing.JTextArea jTextArea34;
    private javax.swing.JTextArea jTextArea35;
    private javax.swing.JTextArea jTextArea36;
    private javax.swing.JTextArea jTextArea37;
    private javax.swing.JTextArea jTextArea38;
    private javax.swing.JTextArea jTextArea39;
    private javax.swing.JTextArea jTextArea4;
    private javax.swing.JTextArea jTextArea6;
    private javax.swing.JTextArea jTextArea7;
    private javax.swing.JTextArea jTextArea8;
    private javax.swing.JTextArea jTextArea9;
    // End of variables declaration//GEN-END:variables
}
