package Secciones;

import javax.swing.ImageIcon;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author aarui
 */
public class NueveDos extends javax.swing.JFrame {

    /**
     * Creates new form NueveDos
     */
    public NueveDos() {
        initComponents();
        setLocationRelativeTo(null);
        ImageIcon ii;
        ii=new ImageIcon(this.getClass().getResource("/Imagenes/HORARIO.png"));
        this.setIconImage(ii.getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextArea26 = new javax.swing.JTextArea();
        jTextArea42 = new javax.swing.JTextArea();
        jTextArea33 = new javax.swing.JTextArea();
        jTextArea50 = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        jTextArea46 = new javax.swing.JTextArea();
        jTextArea38 = new javax.swing.JTextArea();
        jTextArea24 = new javax.swing.JTextArea();
        jTextArea18 = new javax.swing.JTextArea();
        jTextArea20 = new javax.swing.JTextArea();
        jTextArea43 = new javax.swing.JTextArea();
        jTextArea29 = new javax.swing.JTextArea();
        jTextArea21 = new javax.swing.JTextArea();
        jTextArea45 = new javax.swing.JTextArea();
        jTextArea44 = new javax.swing.JTextArea();
        jTextArea52 = new javax.swing.JTextArea();
        jTextArea49 = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        jTextArea48 = new javax.swing.JTextArea();
        jTextArea51 = new javax.swing.JTextArea();
        jTextArea39 = new javax.swing.JTextArea();
        jTextArea36 = new javax.swing.JTextArea();
        jTextArea47 = new javax.swing.JTextArea();
        jTextArea31 = new javax.swing.JTextArea();
        jTextArea41 = new javax.swing.JTextArea();
        jTextArea28 = new javax.swing.JTextArea();
        jTextArea25 = new javax.swing.JTextArea();
        jTextArea22 = new javax.swing.JTextArea();
        jLabel9 = new javax.swing.JLabel();
        jTextArea23 = new javax.swing.JTextArea();
        jTextArea40 = new javax.swing.JTextArea();
        jTextArea37 = new javax.swing.JTextArea();
        jTextArea27 = new javax.swing.JTextArea();
        jTextArea34 = new javax.swing.JTextArea();
        jTextArea30 = new javax.swing.JTextArea();
        jTextArea35 = new javax.swing.JTextArea();
        jTextArea32 = new javax.swing.JTextArea();
        jTextArea19 = new javax.swing.JTextArea();
        Lunes7 = new javax.swing.JLabel();
        Lunes6 = new javax.swing.JLabel();
        Lunes5 = new javax.swing.JLabel();
        Lunes4 = new javax.swing.JLabel();
        Lunes8 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setLayout(null);

        jTextArea26.setEditable(false);
        jTextArea26.setBackground(new java.awt.Color(153, 255, 255));
        jTextArea26.setColumns(20);
        jTextArea26.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jTextArea26.setRows(5);
        jTextArea26.setText("Libre");
        jTextArea26.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jTextArea26);
        jTextArea26.setBounds(510, 420, 100, 30);

        jTextArea42.setEditable(false);
        jTextArea42.setBackground(new java.awt.Color(153, 255, 255));
        jTextArea42.setColumns(20);
        jTextArea42.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jTextArea42.setRows(5);
        jTextArea42.setText("Inglés\nconversacional");
        jTextArea42.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextArea42.setMinimumSize(new java.awt.Dimension(60, 11));
        jPanel1.add(jTextArea42);
        jTextArea42.setBounds(410, 410, 100, 40);

        jTextArea33.setEditable(false);
        jTextArea33.setBackground(new java.awt.Color(153, 255, 255));
        jTextArea33.setColumns(20);
        jTextArea33.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jTextArea33.setRows(5);
        jTextArea33.setText("Matemáticas");
        jTextArea33.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jTextArea33);
        jTextArea33.setBounds(510, 370, 100, 50);

        jTextArea50.setEditable(false);
        jTextArea50.setBackground(new java.awt.Color(153, 255, 255));
        jTextArea50.setColumns(20);
        jTextArea50.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jTextArea50.setRows(5);
        jTextArea50.setText("Inglés\nconversacional");
        jTextArea50.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextArea50.setMinimumSize(new java.awt.Dimension(60, 11));
        jPanel1.add(jTextArea50);
        jTextArea50.setBounds(410, 370, 100, 40);

        jLabel7.setBackground(new java.awt.Color(102, 153, 255));
        jLabel7.setFont(new java.awt.Font("DialogInput", 1, 18)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Receso");
        jLabel7.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLabel7.setOpaque(true);
        jPanel1.add(jLabel7);
        jLabel7.setBounds(110, 340, 500, 30);

        jTextArea46.setEditable(false);
        jTextArea46.setBackground(new java.awt.Color(153, 255, 255));
        jTextArea46.setColumns(20);
        jTextArea46.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jTextArea46.setRows(5);
        jTextArea46.setText("Español");
        jTextArea46.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jTextArea46);
        jTextArea46.setBounds(310, 370, 100, 80);

        jTextArea38.setEditable(false);
        jTextArea38.setBackground(new java.awt.Color(153, 255, 255));
        jTextArea38.setColumns(20);
        jTextArea38.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jTextArea38.setRows(5);
        jTextArea38.setText("Herramientas\nde progra-B");
        jTextArea38.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextArea38.setMinimumSize(new java.awt.Dimension(60, 11));
        jPanel1.add(jTextArea38);
        jTextArea38.setBounds(210, 410, 100, 40);

        jTextArea24.setEditable(false);
        jTextArea24.setBackground(new java.awt.Color(153, 255, 255));
        jTextArea24.setColumns(20);
        jTextArea24.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jTextArea24.setRows(5);
        jTextArea24.setText("Conociendo \nlos negocios-A");
        jTextArea24.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextArea24.setMinimumSize(new java.awt.Dimension(60, 11));
        jPanel1.add(jTextArea24);
        jTextArea24.setBounds(210, 370, 100, 40);

        jTextArea18.setEditable(false);
        jTextArea18.setBackground(new java.awt.Color(153, 255, 255));
        jTextArea18.setColumns(20);
        jTextArea18.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jTextArea18.setRows(5);
        jTextArea18.setText("Ciencias");
        jTextArea18.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jTextArea18);
        jTextArea18.setBounds(110, 370, 100, 80);

        jTextArea20.setEditable(false);
        jTextArea20.setBackground(new java.awt.Color(153, 255, 255));
        jTextArea20.setColumns(20);
        jTextArea20.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jTextArea20.setRows(5);
        jTextArea20.setText("Matemáticas");
        jTextArea20.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jTextArea20);
        jTextArea20.setBounds(110, 260, 100, 80);

        jTextArea43.setEditable(false);
        jTextArea43.setBackground(new java.awt.Color(153, 255, 255));
        jTextArea43.setColumns(20);
        jTextArea43.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jTextArea43.setRows(5);
        jTextArea43.setText("Herramientas\nde progra-B");
        jTextArea43.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextArea43.setMinimumSize(new java.awt.Dimension(60, 11));
        jPanel1.add(jTextArea43);
        jTextArea43.setBounds(210, 300, 100, 40);

        jTextArea29.setEditable(false);
        jTextArea29.setBackground(new java.awt.Color(153, 255, 255));
        jTextArea29.setColumns(20);
        jTextArea29.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jTextArea29.setRows(5);
        jTextArea29.setText("Conociendo \nlos negocios-A");
        jTextArea29.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextArea29.setMinimumSize(new java.awt.Dimension(60, 11));
        jPanel1.add(jTextArea29);
        jTextArea29.setBounds(210, 260, 100, 40);

        jTextArea21.setEditable(false);
        jTextArea21.setBackground(new java.awt.Color(153, 255, 255));
        jTextArea21.setColumns(20);
        jTextArea21.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jTextArea21.setRows(5);
        jTextArea21.setText("Inglés");
        jTextArea21.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jTextArea21);
        jTextArea21.setBounds(310, 260, 100, 80);

        jTextArea45.setEditable(false);
        jTextArea45.setBackground(new java.awt.Color(153, 255, 255));
        jTextArea45.setColumns(20);
        jTextArea45.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jTextArea45.setRows(5);
        jTextArea45.setText("Inglés\nconversacional");
        jTextArea45.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextArea45.setMinimumSize(new java.awt.Dimension(60, 11));
        jPanel1.add(jTextArea45);
        jTextArea45.setBounds(410, 300, 100, 40);

        jTextArea44.setEditable(false);
        jTextArea44.setBackground(new java.awt.Color(153, 255, 255));
        jTextArea44.setColumns(20);
        jTextArea44.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jTextArea44.setRows(5);
        jTextArea44.setText("Inglés\nconversacional");
        jTextArea44.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextArea44.setMinimumSize(new java.awt.Dimension(60, 11));
        jPanel1.add(jTextArea44);
        jTextArea44.setBounds(410, 260, 100, 40);

        jTextArea52.setEditable(false);
        jTextArea52.setBackground(new java.awt.Color(153, 255, 255));
        jTextArea52.setColumns(20);
        jTextArea52.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jTextArea52.setRows(5);
        jTextArea52.setText("Libre");
        jTextArea52.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jTextArea52);
        jTextArea52.setBounds(510, 310, 100, 30);

        jTextArea49.setEditable(false);
        jTextArea49.setBackground(new java.awt.Color(153, 255, 255));
        jTextArea49.setColumns(20);
        jTextArea49.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jTextArea49.setRows(5);
        jTextArea49.setText("Educ.Músical");
        jTextArea49.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jTextArea49);
        jTextArea49.setBounds(510, 260, 100, 50);

        jLabel8.setBackground(new java.awt.Color(102, 153, 255));
        jLabel8.setFont(new java.awt.Font("DialogInput", 1, 18)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Almuerzo");
        jLabel8.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLabel8.setOpaque(true);
        jPanel1.add(jLabel8);
        jLabel8.setBounds(110, 230, 500, 30);

        jTextArea48.setEditable(false);
        jTextArea48.setBackground(new java.awt.Color(153, 255, 255));
        jTextArea48.setColumns(20);
        jTextArea48.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jTextArea48.setRows(5);
        jTextArea48.setText("Est.Sociales");
        jTextArea48.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jTextArea48);
        jTextArea48.setBounds(510, 180, 100, 50);

        jTextArea51.setEditable(false);
        jTextArea51.setBackground(new java.awt.Color(153, 255, 255));
        jTextArea51.setColumns(20);
        jTextArea51.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jTextArea51.setRows(5);
        jTextArea51.setText("Libre");
        jTextArea51.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jTextArea51);
        jTextArea51.setBounds(510, 150, 100, 30);

        jTextArea39.setEditable(false);
        jTextArea39.setBackground(new java.awt.Color(153, 255, 255));
        jTextArea39.setColumns(20);
        jTextArea39.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jTextArea39.setRows(5);
        jTextArea39.setText("Ciencias");
        jTextArea39.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jTextArea39);
        jTextArea39.setBounds(410, 150, 100, 30);

        jTextArea36.setEditable(false);
        jTextArea36.setBackground(new java.awt.Color(153, 255, 255));
        jTextArea36.setColumns(20);
        jTextArea36.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jTextArea36.setRows(5);
        jTextArea36.setText("Español");
        jTextArea36.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jTextArea36);
        jTextArea36.setBounds(410, 180, 100, 50);

        jTextArea47.setEditable(false);
        jTextArea47.setBackground(new java.awt.Color(153, 255, 255));
        jTextArea47.setColumns(20);
        jTextArea47.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jTextArea47.setRows(5);
        jTextArea47.setText("Educ.Física");
        jTextArea47.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jTextArea47);
        jTextArea47.setBounds(310, 180, 100, 50);

        jTextArea31.setEditable(false);
        jTextArea31.setBackground(new java.awt.Color(153, 255, 255));
        jTextArea31.setColumns(20);
        jTextArea31.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jTextArea31.setRows(5);
        jTextArea31.setText("Orientación");
        jTextArea31.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jTextArea31);
        jTextArea31.setBounds(310, 150, 100, 30);

        jTextArea41.setEditable(false);
        jTextArea41.setBackground(new java.awt.Color(153, 255, 255));
        jTextArea41.setColumns(20);
        jTextArea41.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jTextArea41.setRows(5);
        jTextArea41.setText("Herramientas\nde progra-A");
        jTextArea41.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextArea41.setMinimumSize(new java.awt.Dimension(60, 11));
        jPanel1.add(jTextArea41);
        jTextArea41.setBounds(210, 150, 100, 40);

        jTextArea28.setEditable(false);
        jTextArea28.setBackground(new java.awt.Color(153, 255, 255));
        jTextArea28.setColumns(20);
        jTextArea28.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jTextArea28.setRows(5);
        jTextArea28.setText("Conociendo \nlos negocios-B");
        jTextArea28.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextArea28.setMinimumSize(new java.awt.Dimension(60, 11));
        jPanel1.add(jTextArea28);
        jTextArea28.setBounds(210, 190, 100, 40);

        jTextArea25.setEditable(false);
        jTextArea25.setBackground(new java.awt.Color(153, 255, 255));
        jTextArea25.setColumns(20);
        jTextArea25.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jTextArea25.setRows(5);
        jTextArea25.setText("Cívica");
        jTextArea25.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jTextArea25);
        jTextArea25.setBounds(110, 180, 100, 50);

        jTextArea22.setEditable(false);
        jTextArea22.setBackground(new java.awt.Color(153, 255, 255));
        jTextArea22.setColumns(20);
        jTextArea22.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jTextArea22.setRows(5);
        jTextArea22.setText("Educ.Religiosa");
        jTextArea22.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jTextArea22);
        jTextArea22.setBounds(110, 150, 100, 30);

        jLabel9.setBackground(new java.awt.Color(102, 153, 255));
        jLabel9.setFont(new java.awt.Font("DialogInput", 1, 18)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Receso");
        jLabel9.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLabel9.setOpaque(true);
        jPanel1.add(jLabel9);
        jLabel9.setBounds(110, 120, 500, 30);

        jTextArea23.setEditable(false);
        jTextArea23.setBackground(new java.awt.Color(153, 255, 255));
        jTextArea23.setColumns(20);
        jTextArea23.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jTextArea23.setRows(5);
        jTextArea23.setText("Fortalecimiento");
        jTextArea23.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jTextArea23);
        jTextArea23.setBounds(110, 90, 100, 30);

        jTextArea40.setEditable(false);
        jTextArea40.setBackground(new java.awt.Color(153, 255, 255));
        jTextArea40.setColumns(20);
        jTextArea40.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jTextArea40.setRows(5);
        jTextArea40.setText("Libre");
        jTextArea40.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jTextArea40);
        jTextArea40.setBounds(110, 40, 100, 50);

        jTextArea37.setEditable(false);
        jTextArea37.setBackground(new java.awt.Color(153, 255, 255));
        jTextArea37.setColumns(20);
        jTextArea37.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jTextArea37.setRows(5);
        jTextArea37.setText("Herramientas\nde progra-A");
        jTextArea37.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextArea37.setMinimumSize(new java.awt.Dimension(60, 11));
        jPanel1.add(jTextArea37);
        jTextArea37.setBounds(210, 40, 100, 40);

        jTextArea27.setEditable(false);
        jTextArea27.setBackground(new java.awt.Color(153, 255, 255));
        jTextArea27.setColumns(20);
        jTextArea27.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jTextArea27.setRows(5);
        jTextArea27.setText("Conociendo \nlos negocios-B");
        jTextArea27.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextArea27.setMinimumSize(new java.awt.Dimension(60, 11));
        jPanel1.add(jTextArea27);
        jTextArea27.setBounds(210, 80, 100, 40);

        jTextArea34.setEditable(false);
        jTextArea34.setBackground(new java.awt.Color(153, 255, 255));
        jTextArea34.setColumns(20);
        jTextArea34.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jTextArea34.setRows(5);
        jTextArea34.setText("Est.Sociales");
        jTextArea34.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jTextArea34);
        jTextArea34.setBounds(310, 70, 100, 50);

        jTextArea30.setEditable(false);
        jTextArea30.setBackground(new java.awt.Color(153, 255, 255));
        jTextArea30.setColumns(20);
        jTextArea30.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jTextArea30.setRows(5);
        jTextArea30.setText("Guía");
        jTextArea30.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jTextArea30);
        jTextArea30.setBounds(310, 40, 100, 30);

        jTextArea35.setEditable(false);
        jTextArea35.setBackground(new java.awt.Color(153, 255, 255));
        jTextArea35.setColumns(20);
        jTextArea35.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jTextArea35.setRows(5);
        jTextArea35.setText("Informatica\neducativa");
        jTextArea35.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jTextArea35);
        jTextArea35.setBounds(410, 40, 100, 50);

        jTextArea32.setEditable(false);
        jTextArea32.setBackground(new java.awt.Color(153, 255, 255));
        jTextArea32.setColumns(20);
        jTextArea32.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jTextArea32.setRows(5);
        jTextArea32.setText("Ciencias");
        jTextArea32.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jTextArea32);
        jTextArea32.setBounds(410, 90, 100, 30);

        jTextArea19.setEditable(false);
        jTextArea19.setBackground(new java.awt.Color(153, 255, 255));
        jTextArea19.setColumns(20);
        jTextArea19.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jTextArea19.setRows(5);
        jTextArea19.setText("Frances");
        jTextArea19.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jTextArea19);
        jTextArea19.setBounds(510, 40, 100, 80);

        Lunes7.setBackground(new java.awt.Color(153, 204, 255));
        Lunes7.setText("Viernes");
        Lunes7.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Lunes7.setInheritsPopupMenu(false);
        Lunes7.setOpaque(true);
        jPanel1.add(Lunes7);
        Lunes7.setBounds(510, 10, 100, 20);

        Lunes6.setBackground(new java.awt.Color(153, 204, 255));
        Lunes6.setText("Jueves");
        Lunes6.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Lunes6.setInheritsPopupMenu(false);
        Lunes6.setOpaque(true);
        jPanel1.add(Lunes6);
        Lunes6.setBounds(410, 10, 100, 20);

        Lunes5.setBackground(new java.awt.Color(153, 204, 255));
        Lunes5.setText("Miercoles");
        Lunes5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Lunes5.setInheritsPopupMenu(false);
        Lunes5.setOpaque(true);
        jPanel1.add(Lunes5);
        Lunes5.setBounds(310, 10, 100, 20);

        Lunes4.setBackground(new java.awt.Color(153, 204, 255));
        Lunes4.setText("Martes");
        Lunes4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Lunes4.setInheritsPopupMenu(false);
        Lunes4.setOpaque(true);
        jPanel1.add(Lunes4);
        Lunes4.setBounds(210, 10, 100, 20);

        Lunes8.setBackground(new java.awt.Color(153, 204, 255));
        Lunes8.setText("Lunes");
        Lunes8.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Lunes8.setInheritsPopupMenu(false);
        Lunes8.setOpaque(true);
        jPanel1.add(Lunes8);
        Lunes8.setBounds(110, 10, 100, 20);

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel26.setText("7:00 a 7:40");
        jPanel1.add(jLabel26);
        jLabel26.setBounds(10, 40, 60, 13);

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel17.setText("7:40 a 8:20");
        jPanel1.add(jLabel17);
        jLabel17.setBounds(10, 70, 60, 13);

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel16.setText("8:20 a 9:00");
        jPanel1.add(jLabel16);
        jLabel16.setBounds(10, 100, 60, 20);

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel18.setText("9:20 a 10:00");
        jPanel1.add(jLabel18);
        jLabel18.setBounds(10, 150, 70, 13);

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel20.setText("10:00 a 10:40");
        jPanel1.add(jLabel20);
        jLabel20.setBounds(10, 180, 80, 13);

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel21.setText("10:40 a 11:20");
        jPanel1.add(jLabel21);
        jLabel21.setBounds(10, 210, 74, 13);

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel22.setText("12:00 a 12:40");
        jPanel1.add(jLabel22);
        jLabel22.setBounds(10, 260, 80, 13);

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel23.setText("12:40 a 1:20");
        jPanel1.add(jLabel23);
        jLabel23.setBounds(10, 290, 70, 13);

        jLabel29.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel29.setText("1:20 a 2:00");
        jPanel1.add(jLabel29);
        jLabel29.setBounds(10, 320, 60, 13);

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel19.setText("2:20 a 3:00");
        jPanel1.add(jLabel19);
        jLabel19.setBounds(10, 370, 60, 13);

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel27.setText("3:00 a 3:40");
        jPanel1.add(jLabel27);
        jLabel27.setBounds(10, 400, 60, 13);

        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel28.setText("3:40 a 4:20");
        jPanel1.add(jLabel28);
        jLabel28.setBounds(10, 430, 60, 13);

        jButton1.setBackground(new java.awt.Color(153, 255, 255));
        jButton1.setText("Atras");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(0, 0, 70, 24);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 620, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Noveno um = new Noveno();
        um.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Lunes4;
    private javax.swing.JLabel Lunes5;
    private javax.swing.JLabel Lunes6;
    private javax.swing.JLabel Lunes7;
    private javax.swing.JLabel Lunes8;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextArea jTextArea18;
    private javax.swing.JTextArea jTextArea19;
    private javax.swing.JTextArea jTextArea20;
    private javax.swing.JTextArea jTextArea21;
    private javax.swing.JTextArea jTextArea22;
    private javax.swing.JTextArea jTextArea23;
    private javax.swing.JTextArea jTextArea24;
    private javax.swing.JTextArea jTextArea25;
    private javax.swing.JTextArea jTextArea26;
    private javax.swing.JTextArea jTextArea27;
    private javax.swing.JTextArea jTextArea28;
    private javax.swing.JTextArea jTextArea29;
    private javax.swing.JTextArea jTextArea30;
    private javax.swing.JTextArea jTextArea31;
    private javax.swing.JTextArea jTextArea32;
    private javax.swing.JTextArea jTextArea33;
    private javax.swing.JTextArea jTextArea34;
    private javax.swing.JTextArea jTextArea35;
    private javax.swing.JTextArea jTextArea36;
    private javax.swing.JTextArea jTextArea37;
    private javax.swing.JTextArea jTextArea38;
    private javax.swing.JTextArea jTextArea39;
    private javax.swing.JTextArea jTextArea40;
    private javax.swing.JTextArea jTextArea41;
    private javax.swing.JTextArea jTextArea42;
    private javax.swing.JTextArea jTextArea43;
    private javax.swing.JTextArea jTextArea44;
    private javax.swing.JTextArea jTextArea45;
    private javax.swing.JTextArea jTextArea46;
    private javax.swing.JTextArea jTextArea47;
    private javax.swing.JTextArea jTextArea48;
    private javax.swing.JTextArea jTextArea49;
    private javax.swing.JTextArea jTextArea50;
    private javax.swing.JTextArea jTextArea51;
    private javax.swing.JTextArea jTextArea52;
    // End of variables declaration//GEN-END:variables
}
