package Secciones;

import javax.swing.ImageIcon;

/**
 *
 * @author aarui
 */
public class OnceCuatro extends javax.swing.JFrame {

    /**
     * Creates new form OnceTres
     */
    public OnceCuatro() {
        initComponents();
        setLocationRelativeTo(null);
        ImageIcon ii;
        ii=new ImageIcon(this.getClass().getResource("/Imagenes/HORARIO.png"));
        this.setIconImage(ii.getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Lunes = new javax.swing.JLabel();
        Lunes1 = new javax.swing.JLabel();
        Lunes2 = new javax.swing.JLabel();
        Lunes3 = new javax.swing.JLabel();
        Lunes4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextArea3 = new javax.swing.JTextArea();
        jTextArea7 = new javax.swing.JTextArea();
        jTextArea18 = new javax.swing.JTextArea();
        jTextArea20 = new javax.swing.JTextArea();
        jTextArea31 = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jTextArea39 = new javax.swing.JTextArea();
        jTextArea40 = new javax.swing.JTextArea();
        jTextArea44 = new javax.swing.JTextArea();
        jTextArea32 = new javax.swing.JTextArea();
        jTextArea45 = new javax.swing.JTextArea();
        jTextArea46 = new javax.swing.JTextArea();
        jTextArea8 = new javax.swing.JTextArea();
        jTextArea35 = new javax.swing.JTextArea();
        jTextArea64 = new javax.swing.JTextArea();
        jTextArea67 = new javax.swing.JTextArea();
        jTextArea53 = new javax.swing.JTextArea();
        jTextArea59 = new javax.swing.JTextArea();
        jTextArea61 = new javax.swing.JTextArea();
        jTextArea63 = new javax.swing.JTextArea();
        jTextArea69 = new javax.swing.JTextArea();
        jTextArea71 = new javax.swing.JTextArea();
        jTextArea72 = new javax.swing.JTextArea();
        jTextArea80 = new javax.swing.JTextArea();
        jTextArea81 = new javax.swing.JTextArea();
        jTextArea54 = new javax.swing.JTextArea();
        jTextArea36 = new javax.swing.JTextArea();
        jTextArea37 = new javax.swing.JTextArea();
        jTextArea83 = new javax.swing.JTextArea();
        jTextArea84 = new javax.swing.JTextArea();
        jLabel20 = new javax.swing.JLabel();
        jTextArea41 = new javax.swing.JTextArea();
        jTextArea42 = new javax.swing.JTextArea();
        jTextArea65 = new javax.swing.JTextArea();
        jTextArea56 = new javax.swing.JTextArea();
        jTextArea43 = new javax.swing.JTextArea();
        jTextArea57 = new javax.swing.JTextArea();
        jTextArea58 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setLayout(null);

        Lunes.setBackground(new java.awt.Color(153, 204, 255));
        Lunes.setText("Martes");
        Lunes.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Lunes.setInheritsPopupMenu(false);
        Lunes.setOpaque(true);
        jPanel1.add(Lunes);
        Lunes.setBounds(200, 10, 100, 20);

        Lunes1.setBackground(new java.awt.Color(153, 204, 255));
        Lunes1.setText("Viernes");
        Lunes1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Lunes1.setInheritsPopupMenu(false);
        Lunes1.setOpaque(true);
        jPanel1.add(Lunes1);
        Lunes1.setBounds(500, 10, 100, 20);

        Lunes2.setBackground(new java.awt.Color(153, 204, 255));
        Lunes2.setText("Jueves");
        Lunes2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Lunes2.setInheritsPopupMenu(false);
        Lunes2.setOpaque(true);
        jPanel1.add(Lunes2);
        Lunes2.setBounds(400, 10, 100, 20);

        Lunes3.setBackground(new java.awt.Color(153, 204, 255));
        Lunes3.setText("Miercoles");
        Lunes3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Lunes3.setInheritsPopupMenu(false);
        Lunes3.setOpaque(true);
        jPanel1.add(Lunes3);
        Lunes3.setBounds(300, 10, 100, 20);

        Lunes4.setBackground(new java.awt.Color(153, 204, 255));
        Lunes4.setText("Lunes");
        Lunes4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Lunes4.setInheritsPopupMenu(false);
        Lunes4.setOpaque(true);
        jPanel1.add(Lunes4);
        Lunes4.setBounds(100, 10, 100, 20);

        jLabel5.setBackground(new java.awt.Color(102, 153, 255));
        jLabel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLabel5.setOpaque(true);
        jPanel1.add(jLabel5);
        jLabel5.setBounds(100, 330, 500, 30);

        jLabel6.setBackground(new java.awt.Color(102, 153, 255));
        jLabel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLabel6.setOpaque(true);
        jPanel1.add(jLabel6);
        jLabel6.setBounds(100, 220, 500, 30);

        jLabel7.setBackground(new java.awt.Color(102, 153, 255));
        jLabel7.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLabel7.setOpaque(true);
        jPanel1.add(jLabel7);
        jLabel7.setBounds(100, 110, 500, 30);

        jTextArea3.setEditable(false);
        jTextArea3.setBackground(new java.awt.Color(153, 255, 255));
        jTextArea3.setColumns(20);
        jTextArea3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jTextArea3.setRows(5);
        jTextArea3.setText("Matemáticas");
        jTextArea3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jTextArea3);
        jTextArea3.setBounds(300, 30, 100, 80);

        jTextArea7.setEditable(false);
        jTextArea7.setBackground(new java.awt.Color(153, 255, 255));
        jTextArea7.setColumns(20);
        jTextArea7.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jTextArea7.setRows(5);
        jTextArea7.setText("Biología");
        jTextArea7.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jTextArea7);
        jTextArea7.setBounds(400, 250, 100, 80);

        jTextArea18.setEditable(false);
        jTextArea18.setBackground(new java.awt.Color(153, 255, 255));
        jTextArea18.setColumns(20);
        jTextArea18.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jTextArea18.setRows(5);
        jTextArea18.setText("Español");
        jTextArea18.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jTextArea18);
        jTextArea18.setBounds(100, 140, 100, 80);

        jTextArea20.setEditable(false);
        jTextArea20.setBackground(new java.awt.Color(153, 255, 255));
        jTextArea20.setColumns(20);
        jTextArea20.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jTextArea20.setRows(5);
        jTextArea20.setText("Inglés");
        jTextArea20.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jTextArea20);
        jTextArea20.setBounds(100, 250, 100, 80);

        jTextArea31.setEditable(false);
        jTextArea31.setBackground(new java.awt.Color(153, 255, 255));
        jTextArea31.setColumns(20);
        jTextArea31.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jTextArea31.setRows(5);
        jTextArea31.setText("Educ.Músical");
        jTextArea31.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jTextArea31);
        jTextArea31.setBounds(400, 360, 100, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel8.setText("7:40 a 8:20");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(10, 60, 60, 13);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel9.setText("8:20 a 9:00");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(10, 90, 60, 13);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel10.setText("9:20 a 10:00");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(10, 140, 67, 13);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel11.setText("10:00 a 10:40");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(10, 170, 74, 13);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel12.setText("10:40 a 11:20");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(10, 200, 80, 13);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel13.setText("12:00 a 12:40");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(10, 250, 80, 13);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel14.setText("12:40 a 1:20");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(10, 280, 70, 13);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel15.setText("1:20 a 2:00");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(10, 310, 60, 13);

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel16.setText("7:00 a 7:40");
        jPanel1.add(jLabel16);
        jLabel16.setBounds(10, 30, 60, 13);

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel17.setText("2:20 a 3:00");
        jPanel1.add(jLabel17);
        jLabel17.setBounds(10, 360, 60, 13);

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel18.setText("3:00 a 3:40");
        jPanel1.add(jLabel18);
        jLabel18.setBounds(10, 390, 60, 13);

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel19.setText("4:20 a 5:00");
        jPanel1.add(jLabel19);
        jLabel19.setBounds(10, 440, 60, 13);

        jButton1.setBackground(new java.awt.Color(153, 255, 255));
        jButton1.setText("Atras");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(0, 0, 70, 23);

        jTextArea39.setEditable(false);
        jTextArea39.setBackground(new java.awt.Color(153, 255, 255));
        jTextArea39.setColumns(20);
        jTextArea39.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jTextArea39.setRows(5);
        jTextArea39.setText("Educ.Física");
        jTextArea39.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jTextArea39);
        jTextArea39.setBounds(400, 390, 100, 50);

        jTextArea40.setEditable(false);
        jTextArea40.setBackground(new java.awt.Color(153, 255, 255));
        jTextArea40.setColumns(20);
        jTextArea40.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jTextArea40.setRows(5);
        jTextArea40.setText("Educ.Religiosa");
        jTextArea40.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jTextArea40);
        jTextArea40.setBounds(100, 360, 100, 30);

        jTextArea44.setEditable(false);
        jTextArea44.setBackground(new java.awt.Color(153, 255, 255));
        jTextArea44.setColumns(20);
        jTextArea44.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jTextArea44.setRows(5);
        jTextArea44.setText("Cívica");
        jTextArea44.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jTextArea44);
        jTextArea44.setBounds(300, 170, 100, 20);

        jTextArea32.setEditable(false);
        jTextArea32.setBackground(new java.awt.Color(153, 255, 255));
        jTextArea32.setColumns(20);
        jTextArea32.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jTextArea32.setRows(5);
        jTextArea32.setText("Guía");
        jTextArea32.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jTextArea32);
        jTextArea32.setBounds(300, 140, 100, 30);

        jTextArea45.setEditable(false);
        jTextArea45.setBackground(new java.awt.Color(153, 255, 255));
        jTextArea45.setColumns(20);
        jTextArea45.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jTextArea45.setRows(5);
        jTextArea45.setText("Psicología");
        jTextArea45.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jTextArea45);
        jTextArea45.setBounds(300, 190, 100, 30);

        jTextArea46.setEditable(false);
        jTextArea46.setBackground(new java.awt.Color(153, 255, 255));
        jTextArea46.setColumns(20);
        jTextArea46.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jTextArea46.setRows(5);
        jTextArea46.setText("Est.Sociales");
        jTextArea46.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jTextArea46);
        jTextArea46.setBounds(100, 390, 100, 50);

        jTextArea8.setEditable(false);
        jTextArea8.setBackground(new java.awt.Color(153, 255, 255));
        jTextArea8.setColumns(20);
        jTextArea8.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jTextArea8.setRows(5);
        jTextArea8.setText("Quimíca");
        jTextArea8.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jTextArea8);
        jTextArea8.setBounds(100, 30, 100, 80);

        jTextArea35.setEditable(false);
        jTextArea35.setBackground(new java.awt.Color(153, 255, 255));
        jTextArea35.setColumns(20);
        jTextArea35.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jTextArea35.setRows(5);
        jTextArea35.setText("Progra\nmación");
        jTextArea35.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextArea35.setMinimumSize(new java.awt.Dimension(60, 11));
        jPanel1.add(jTextArea35);
        jTextArea35.setBounds(300, 360, 50, 80);

        jTextArea64.setEditable(false);
        jTextArea64.setBackground(new java.awt.Color(153, 255, 255));
        jTextArea64.setColumns(20);
        jTextArea64.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jTextArea64.setRows(5);
        jTextArea64.setText("Ingles \ntécnico\nDibujo");
        jTextArea64.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextArea64.setMinimumSize(new java.awt.Dimension(60, 11));
        jPanel1.add(jTextArea64);
        jTextArea64.setBounds(250, 30, 50, 80);

        jTextArea67.setEditable(false);
        jTextArea67.setBackground(new java.awt.Color(153, 255, 255));
        jTextArea67.setColumns(20);
        jTextArea67.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jTextArea67.setRows(5);
        jTextArea67.setText("Ingles\n técnico\nDesa\nrrollo");
        jTextArea67.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextArea67.setMinimumSize(new java.awt.Dimension(60, 11));
        jPanel1.add(jTextArea67);
        jTextArea67.setBounds(400, 30, 50, 80);

        jTextArea53.setEditable(false);
        jTextArea53.setBackground(new java.awt.Color(153, 255, 255));
        jTextArea53.setColumns(20);
        jTextArea53.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jTextArea53.setRows(5);
        jTextArea53.setText("Dibujo\nasistido");
        jTextArea53.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextArea53.setMinimumSize(new java.awt.Dimension(60, 11));
        jPanel1.add(jTextArea53);
        jTextArea53.setBounds(350, 250, 50, 80);

        jTextArea59.setEditable(false);
        jTextArea59.setBackground(new java.awt.Color(153, 255, 255));
        jTextArea59.setColumns(20);
        jTextArea59.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jTextArea59.setRows(5);
        jTextArea59.setText("Interfaz");
        jTextArea59.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextArea59.setMinimumSize(new java.awt.Dimension(60, 11));
        jPanel1.add(jTextArea59);
        jTextArea59.setBounds(200, 360, 50, 80);

        jTextArea61.setEditable(false);
        jTextArea61.setBackground(new java.awt.Color(153, 255, 255));
        jTextArea61.setColumns(20);
        jTextArea61.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jTextArea61.setRows(5);
        jTextArea61.setText("Interfaz");
        jTextArea61.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextArea61.setMinimumSize(new java.awt.Dimension(60, 11));
        jPanel1.add(jTextArea61);
        jTextArea61.setBounds(350, 360, 50, 80);

        jTextArea63.setEditable(false);
        jTextArea63.setBackground(new java.awt.Color(153, 255, 255));
        jTextArea63.setColumns(20);
        jTextArea63.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jTextArea63.setRows(5);
        jTextArea63.setText("Interfaz");
        jTextArea63.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextArea63.setMinimumSize(new java.awt.Dimension(60, 11));
        jPanel1.add(jTextArea63);
        jTextArea63.setBounds(400, 140, 50, 80);

        jTextArea69.setEditable(false);
        jTextArea69.setBackground(new java.awt.Color(153, 255, 255));
        jTextArea69.setColumns(20);
        jTextArea69.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jTextArea69.setRows(5);
        jTextArea69.setText("Tecnica\nde pre\nsenta\ncion y\nmodelos");
        jTextArea69.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextArea69.setMinimumSize(new java.awt.Dimension(60, 11));
        jPanel1.add(jTextArea69);
        jTextArea69.setBounds(550, 140, 50, 80);

        jTextArea71.setEditable(false);
        jTextArea71.setBackground(new java.awt.Color(153, 255, 255));
        jTextArea71.setColumns(20);
        jTextArea71.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jTextArea71.setRows(5);
        jTextArea71.setText("Interfaz");
        jTextArea71.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextArea71.setMinimumSize(new java.awt.Dimension(60, 11));
        jPanel1.add(jTextArea71);
        jTextArea71.setBounds(200, 250, 50, 80);

        jTextArea72.setEditable(false);
        jTextArea72.setBackground(new java.awt.Color(153, 255, 255));
        jTextArea72.setColumns(20);
        jTextArea72.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jTextArea72.setRows(5);
        jTextArea72.setText("Interfaz");
        jTextArea72.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextArea72.setMinimumSize(new java.awt.Dimension(60, 11));
        jPanel1.add(jTextArea72);
        jTextArea72.setBounds(200, 30, 50, 80);

        jTextArea80.setEditable(false);
        jTextArea80.setBackground(new java.awt.Color(153, 255, 255));
        jTextArea80.setColumns(20);
        jTextArea80.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jTextArea80.setRows(5);
        jTextArea80.setText("Dibujo \nArquitec\ntonico");
        jTextArea80.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextArea80.setMinimumSize(new java.awt.Dimension(60, 11));
        jPanel1.add(jTextArea80);
        jTextArea80.setBounds(250, 140, 50, 80);

        jTextArea81.setEditable(false);
        jTextArea81.setBackground(new java.awt.Color(153, 255, 255));
        jTextArea81.setColumns(20);
        jTextArea81.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jTextArea81.setRows(5);
        jTextArea81.setText("Tecnica\nde pre\nsenta\ncion y\nmodelos");
        jTextArea81.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextArea81.setMinimumSize(new java.awt.Dimension(60, 11));
        jPanel1.add(jTextArea81);
        jTextArea81.setBounds(550, 30, 50, 80);

        jTextArea54.setEditable(false);
        jTextArea54.setBackground(new java.awt.Color(153, 255, 255));
        jTextArea54.setColumns(20);
        jTextArea54.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jTextArea54.setRows(5);
        jTextArea54.setText("Dibujo\nasistido");
        jTextArea54.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextArea54.setMinimumSize(new java.awt.Dimension(60, 11));
        jPanel1.add(jTextArea54);
        jTextArea54.setBounds(550, 360, 50, 80);

        jTextArea36.setEditable(false);
        jTextArea36.setBackground(new java.awt.Color(153, 255, 255));
        jTextArea36.setColumns(20);
        jTextArea36.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jTextArea36.setRows(5);
        jTextArea36.setText("Progra\nmación");
        jTextArea36.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextArea36.setMinimumSize(new java.awt.Dimension(60, 11));
        jPanel1.add(jTextArea36);
        jTextArea36.setBounds(500, 360, 50, 80);

        jTextArea37.setEditable(false);
        jTextArea37.setBackground(new java.awt.Color(153, 255, 255));
        jTextArea37.setColumns(20);
        jTextArea37.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jTextArea37.setRows(5);
        jTextArea37.setText("Progra\nmación");
        jTextArea37.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextArea37.setMinimumSize(new java.awt.Dimension(60, 11));
        jPanel1.add(jTextArea37);
        jTextArea37.setBounds(500, 30, 50, 80);

        jTextArea83.setEditable(false);
        jTextArea83.setBackground(new java.awt.Color(153, 255, 255));
        jTextArea83.setColumns(20);
        jTextArea83.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jTextArea83.setRows(5);
        jTextArea83.setText("Dibujo \nArquitec\ntonico");
        jTextArea83.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextArea83.setMinimumSize(new java.awt.Dimension(60, 11));
        jPanel1.add(jTextArea83);
        jTextArea83.setBounds(250, 250, 50, 80);

        jTextArea84.setEditable(false);
        jTextArea84.setBackground(new java.awt.Color(153, 255, 255));
        jTextArea84.setColumns(20);
        jTextArea84.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jTextArea84.setRows(5);
        jTextArea84.setText("Dibujo \nArquitec\ntonico");
        jTextArea84.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextArea84.setMinimumSize(new java.awt.Dimension(60, 11));
        jPanel1.add(jTextArea84);
        jTextArea84.setBounds(250, 360, 50, 80);

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel20.setText("3:40 a 4:20");
        jPanel1.add(jLabel20);
        jLabel20.setBounds(10, 420, 60, 13);

        jTextArea41.setEditable(false);
        jTextArea41.setBackground(new java.awt.Color(153, 255, 255));
        jTextArea41.setColumns(20);
        jTextArea41.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jTextArea41.setRows(5);
        jTextArea41.setText("Progra\nmación");
        jTextArea41.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextArea41.setMinimumSize(new java.awt.Dimension(60, 11));
        jPanel1.add(jTextArea41);
        jTextArea41.setBounds(500, 140, 50, 80);

        jTextArea42.setEditable(false);
        jTextArea42.setBackground(new java.awt.Color(153, 255, 255));
        jTextArea42.setColumns(20);
        jTextArea42.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jTextArea42.setRows(5);
        jTextArea42.setText("Progra\nmación");
        jTextArea42.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextArea42.setMinimumSize(new java.awt.Dimension(60, 11));
        jPanel1.add(jTextArea42);
        jTextArea42.setBounds(300, 250, 50, 80);

        jTextArea65.setEditable(false);
        jTextArea65.setBackground(new java.awt.Color(153, 255, 255));
        jTextArea65.setColumns(20);
        jTextArea65.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jTextArea65.setRows(5);
        jTextArea65.setText("Interfaz");
        jTextArea65.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextArea65.setMinimumSize(new java.awt.Dimension(60, 11));
        jPanel1.add(jTextArea65);
        jTextArea65.setBounds(200, 140, 50, 80);

        jTextArea56.setEditable(false);
        jTextArea56.setBackground(new java.awt.Color(153, 255, 255));
        jTextArea56.setColumns(20);
        jTextArea56.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jTextArea56.setRows(5);
        jTextArea56.setText("Dibujo\nasistido");
        jTextArea56.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextArea56.setMinimumSize(new java.awt.Dimension(60, 11));
        jPanel1.add(jTextArea56);
        jTextArea56.setBounds(450, 30, 50, 80);

        jTextArea43.setEditable(false);
        jTextArea43.setBackground(new java.awt.Color(153, 255, 255));
        jTextArea43.setColumns(20);
        jTextArea43.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jTextArea43.setRows(5);
        jTextArea43.setText("Progra\nmación");
        jTextArea43.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextArea43.setMinimumSize(new java.awt.Dimension(60, 11));
        jPanel1.add(jTextArea43);
        jTextArea43.setBounds(500, 250, 50, 80);

        jTextArea57.setEditable(false);
        jTextArea57.setBackground(new java.awt.Color(153, 255, 255));
        jTextArea57.setColumns(20);
        jTextArea57.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jTextArea57.setRows(5);
        jTextArea57.setText("Dibujo\nasistido");
        jTextArea57.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextArea57.setMinimumSize(new java.awt.Dimension(60, 11));
        jPanel1.add(jTextArea57);
        jTextArea57.setBounds(450, 140, 50, 80);

        jTextArea58.setEditable(false);
        jTextArea58.setBackground(new java.awt.Color(153, 255, 255));
        jTextArea58.setColumns(20);
        jTextArea58.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jTextArea58.setRows(5);
        jTextArea58.setText("Dibujo\nasistido");
        jTextArea58.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextArea58.setMinimumSize(new java.awt.Dimension(60, 11));
        jPanel1.add(jTextArea58);
        jTextArea58.setBounds(550, 250, 50, 80);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 613, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 460, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Undecimo um = new Undecimo();
        um.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Lunes;
    private javax.swing.JLabel Lunes1;
    private javax.swing.JLabel Lunes2;
    private javax.swing.JLabel Lunes3;
    private javax.swing.JLabel Lunes4;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextArea jTextArea18;
    private javax.swing.JTextArea jTextArea20;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextArea jTextArea31;
    private javax.swing.JTextArea jTextArea32;
    private javax.swing.JTextArea jTextArea35;
    private javax.swing.JTextArea jTextArea36;
    private javax.swing.JTextArea jTextArea37;
    private javax.swing.JTextArea jTextArea39;
    private javax.swing.JTextArea jTextArea40;
    private javax.swing.JTextArea jTextArea41;
    private javax.swing.JTextArea jTextArea42;
    private javax.swing.JTextArea jTextArea43;
    private javax.swing.JTextArea jTextArea44;
    private javax.swing.JTextArea jTextArea45;
    private javax.swing.JTextArea jTextArea46;
    private javax.swing.JTextArea jTextArea53;
    private javax.swing.JTextArea jTextArea54;
    private javax.swing.JTextArea jTextArea56;
    private javax.swing.JTextArea jTextArea57;
    private javax.swing.JTextArea jTextArea58;
    private javax.swing.JTextArea jTextArea59;
    private javax.swing.JTextArea jTextArea61;
    private javax.swing.JTextArea jTextArea63;
    private javax.swing.JTextArea jTextArea64;
    private javax.swing.JTextArea jTextArea65;
    private javax.swing.JTextArea jTextArea67;
    private javax.swing.JTextArea jTextArea69;
    private javax.swing.JTextArea jTextArea7;
    private javax.swing.JTextArea jTextArea71;
    private javax.swing.JTextArea jTextArea72;
    private javax.swing.JTextArea jTextArea8;
    private javax.swing.JTextArea jTextArea80;
    private javax.swing.JTextArea jTextArea81;
    private javax.swing.JTextArea jTextArea83;
    private javax.swing.JTextArea jTextArea84;
    // End of variables declaration//GEN-END:variables
}
