package Secciones;

import javax.swing.ImageIcon;

/**
 *
 * @author aarui
 */
public class OnceSeis extends javax.swing.JFrame {

    /**
     * Creates new form OnceDos
     */
    public OnceSeis() {
        initComponents();
        setLocationRelativeTo(null);
        ImageIcon ii;
        ii=new ImageIcon(this.getClass().getResource("/Imagenes/HORARIO.png"));
        this.setIconImage(ii.getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        Lunes = new javax.swing.JLabel();
        Lunes1 = new javax.swing.JLabel();
        Lunes2 = new javax.swing.JLabel();
        Lunes3 = new javax.swing.JLabel();
        Lunes4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextArea3 = new javax.swing.JTextArea();
        jTextArea7 = new javax.swing.JTextArea();
        jTextArea18 = new javax.swing.JTextArea();
        jTextArea20 = new javax.swing.JTextArea();
        jTextArea31 = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jTextArea39 = new javax.swing.JTextArea();
        jTextArea40 = new javax.swing.JTextArea();
        jTextArea44 = new javax.swing.JTextArea();
        jTextArea32 = new javax.swing.JTextArea();
        jTextArea45 = new javax.swing.JTextArea();
        jTextArea46 = new javax.swing.JTextArea();
        jTextArea8 = new javax.swing.JTextArea();
        jTextArea57 = new javax.swing.JTextArea();
        jTextArea64 = new javax.swing.JTextArea();
        jTextArea68 = new javax.swing.JTextArea();
        jTextArea63 = new javax.swing.JTextArea();
        jLabel20 = new javax.swing.JLabel();
        jTextArea74 = new javax.swing.JTextArea();
        jTextArea75 = new javax.swing.JTextArea();
        jTextArea58 = new javax.swing.JTextArea();
        jTextArea76 = new javax.swing.JTextArea();
        jTextArea62 = new javax.swing.JTextArea();
        jTextArea77 = new javax.swing.JTextArea();
        jTextArea78 = new javax.swing.JTextArea();
        jTextArea79 = new javax.swing.JTextArea();
        jTextArea80 = new javax.swing.JTextArea();
        jTextArea47 = new javax.swing.JTextArea();
        jTextArea81 = new javax.swing.JTextArea();
        jTextArea84 = new javax.swing.JTextArea();
        jTextArea85 = new javax.swing.JTextArea();
        jTextArea86 = new javax.swing.JTextArea();
        jTextArea87 = new javax.swing.JTextArea();
        jTextArea88 = new javax.swing.JTextArea();
        jTextArea89 = new javax.swing.JTextArea();
        jTextArea90 = new javax.swing.JTextArea();
        jTextArea91 = new javax.swing.JTextArea();
        jTextArea93 = new javax.swing.JTextArea();
        jTextArea94 = new javax.swing.JTextArea();
        jTextArea95 = new javax.swing.JTextArea();
        jTextArea96 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));
        jPanel2.setLayout(null);

        Lunes.setBackground(new java.awt.Color(153, 204, 255));
        Lunes.setText("Martes");
        Lunes.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Lunes.setInheritsPopupMenu(false);
        Lunes.setOpaque(true);
        jPanel2.add(Lunes);
        Lunes.setBounds(200, 10, 100, 20);

        Lunes1.setBackground(new java.awt.Color(153, 204, 255));
        Lunes1.setText("Viernes");
        Lunes1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Lunes1.setInheritsPopupMenu(false);
        Lunes1.setOpaque(true);
        jPanel2.add(Lunes1);
        Lunes1.setBounds(500, 10, 100, 20);

        Lunes2.setBackground(new java.awt.Color(153, 204, 255));
        Lunes2.setText("Jueves");
        Lunes2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Lunes2.setInheritsPopupMenu(false);
        Lunes2.setOpaque(true);
        jPanel2.add(Lunes2);
        Lunes2.setBounds(400, 10, 100, 20);

        Lunes3.setBackground(new java.awt.Color(153, 204, 255));
        Lunes3.setText("Miercoles");
        Lunes3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Lunes3.setInheritsPopupMenu(false);
        Lunes3.setOpaque(true);
        jPanel2.add(Lunes3);
        Lunes3.setBounds(300, 10, 100, 20);

        Lunes4.setBackground(new java.awt.Color(153, 204, 255));
        Lunes4.setText("Lunes");
        Lunes4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Lunes4.setInheritsPopupMenu(false);
        Lunes4.setOpaque(true);
        jPanel2.add(Lunes4);
        Lunes4.setBounds(100, 10, 100, 20);

        jLabel5.setBackground(new java.awt.Color(102, 153, 255));
        jLabel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLabel5.setOpaque(true);
        jPanel2.add(jLabel5);
        jLabel5.setBounds(100, 330, 500, 30);

        jLabel6.setBackground(new java.awt.Color(102, 153, 255));
        jLabel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLabel6.setOpaque(true);
        jPanel2.add(jLabel6);
        jLabel6.setBounds(100, 220, 500, 30);

        jLabel7.setBackground(new java.awt.Color(102, 153, 255));
        jLabel7.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLabel7.setOpaque(true);
        jPanel2.add(jLabel7);
        jLabel7.setBounds(100, 110, 500, 30);

        jTextArea3.setEditable(false);
        jTextArea3.setBackground(new java.awt.Color(153, 255, 255));
        jTextArea3.setColumns(20);
        jTextArea3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jTextArea3.setRows(5);
        jTextArea3.setText("Matemáticas");
        jTextArea3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.add(jTextArea3);
        jTextArea3.setBounds(500, 250, 100, 80);

        jTextArea7.setEditable(false);
        jTextArea7.setBackground(new java.awt.Color(153, 255, 255));
        jTextArea7.setColumns(20);
        jTextArea7.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jTextArea7.setRows(5);
        jTextArea7.setText("Biología");
        jTextArea7.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.add(jTextArea7);
        jTextArea7.setBounds(100, 250, 100, 80);

        jTextArea18.setEditable(false);
        jTextArea18.setBackground(new java.awt.Color(153, 255, 255));
        jTextArea18.setColumns(20);
        jTextArea18.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jTextArea18.setRows(5);
        jTextArea18.setText("Español");
        jTextArea18.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.add(jTextArea18);
        jTextArea18.setBounds(200, 140, 100, 80);

        jTextArea20.setEditable(false);
        jTextArea20.setBackground(new java.awt.Color(153, 255, 255));
        jTextArea20.setColumns(20);
        jTextArea20.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jTextArea20.setRows(5);
        jTextArea20.setText("Inglés");
        jTextArea20.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.add(jTextArea20);
        jTextArea20.setBounds(500, 360, 100, 80);

        jTextArea31.setEditable(false);
        jTextArea31.setBackground(new java.awt.Color(153, 255, 255));
        jTextArea31.setColumns(20);
        jTextArea31.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jTextArea31.setRows(5);
        jTextArea31.setText("Educ.Músical");
        jTextArea31.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.add(jTextArea31);
        jTextArea31.setBounds(100, 380, 100, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel8.setText("7:40 a 8:20");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(10, 60, 60, 13);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel9.setText("8:20 a 9:00");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(10, 90, 60, 13);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel10.setText("9:20 a 10:00");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(10, 140, 67, 13);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel11.setText("10:00 a 10:40");
        jPanel2.add(jLabel11);
        jLabel11.setBounds(10, 170, 74, 13);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel12.setText("10:40 a 11:20");
        jPanel2.add(jLabel12);
        jLabel12.setBounds(10, 200, 80, 13);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel13.setText("12:00 a 12:40");
        jPanel2.add(jLabel13);
        jLabel13.setBounds(10, 250, 80, 13);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel14.setText("12:40 a 1:20");
        jPanel2.add(jLabel14);
        jLabel14.setBounds(10, 280, 70, 13);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel15.setText("1:20 a 2:00");
        jPanel2.add(jLabel15);
        jLabel15.setBounds(10, 310, 60, 13);

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel16.setText("7:00 a 7:40");
        jPanel2.add(jLabel16);
        jLabel16.setBounds(10, 30, 60, 13);

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel17.setText("2:20 a 3:00");
        jPanel2.add(jLabel17);
        jLabel17.setBounds(10, 360, 60, 13);

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel18.setText("3:00 a 3:40");
        jPanel2.add(jLabel18);
        jLabel18.setBounds(10, 390, 60, 13);

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel19.setText("3:40 a 4:20");
        jPanel2.add(jLabel19);
        jLabel19.setBounds(10, 420, 60, 13);

        jButton1.setBackground(new java.awt.Color(153, 255, 255));
        jButton1.setText("Atras");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);
        jButton1.setBounds(0, 0, 70, 23);

        jTextArea39.setEditable(false);
        jTextArea39.setBackground(new java.awt.Color(153, 255, 255));
        jTextArea39.setColumns(20);
        jTextArea39.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jTextArea39.setRows(5);
        jTextArea39.setText("Educ.Física");
        jTextArea39.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.add(jTextArea39);
        jTextArea39.setBounds(300, 250, 100, 50);

        jTextArea40.setEditable(false);
        jTextArea40.setBackground(new java.awt.Color(153, 255, 255));
        jTextArea40.setColumns(20);
        jTextArea40.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jTextArea40.setRows(5);
        jTextArea40.setText("Educ.Religiosa");
        jTextArea40.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.add(jTextArea40);
        jTextArea40.setBounds(100, 410, 100, 30);

        jTextArea44.setEditable(false);
        jTextArea44.setBackground(new java.awt.Color(153, 255, 255));
        jTextArea44.setColumns(20);
        jTextArea44.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jTextArea44.setRows(5);
        jTextArea44.setText("Cívica");
        jTextArea44.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.add(jTextArea44);
        jTextArea44.setBounds(300, 410, 100, 30);

        jTextArea32.setEditable(false);
        jTextArea32.setBackground(new java.awt.Color(153, 255, 255));
        jTextArea32.setColumns(20);
        jTextArea32.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jTextArea32.setRows(5);
        jTextArea32.setText("Guía");
        jTextArea32.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.add(jTextArea32);
        jTextArea32.setBounds(100, 360, 100, 20);

        jTextArea45.setEditable(false);
        jTextArea45.setBackground(new java.awt.Color(153, 255, 255));
        jTextArea45.setColumns(20);
        jTextArea45.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jTextArea45.setRows(5);
        jTextArea45.setText("Psicología");
        jTextArea45.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.add(jTextArea45);
        jTextArea45.setBounds(300, 380, 100, 30);

        jTextArea46.setEditable(false);
        jTextArea46.setBackground(new java.awt.Color(153, 255, 255));
        jTextArea46.setColumns(20);
        jTextArea46.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jTextArea46.setRows(5);
        jTextArea46.setText("Est.Sociales");
        jTextArea46.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.add(jTextArea46);
        jTextArea46.setBounds(300, 300, 100, 30);

        jTextArea8.setEditable(false);
        jTextArea8.setBackground(new java.awt.Color(153, 255, 255));
        jTextArea8.setColumns(20);
        jTextArea8.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jTextArea8.setRows(5);
        jTextArea8.setText("Quimíca");
        jTextArea8.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.add(jTextArea8);
        jTextArea8.setBounds(200, 30, 100, 80);

        jTextArea57.setEditable(false);
        jTextArea57.setBackground(new java.awt.Color(153, 255, 255));
        jTextArea57.setColumns(20);
        jTextArea57.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jTextArea57.setRows(5);
        jTextArea57.setText("Contex\nto\nlegal");
        jTextArea57.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextArea57.setMinimumSize(new java.awt.Dimension(60, 11));
        jPanel2.add(jTextArea57);
        jTextArea57.setBounds(250, 360, 50, 80);

        jTextArea64.setEditable(false);
        jTextArea64.setBackground(new java.awt.Color(153, 255, 255));
        jTextArea64.setColumns(20);
        jTextArea64.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jTextArea64.setRows(5);
        jTextArea64.setText("Ingles \ntécnico");
        jTextArea64.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextArea64.setMinimumSize(new java.awt.Dimension(60, 11));
        jPanel2.add(jTextArea64);
        jTextArea64.setBounds(400, 360, 50, 80);

        jTextArea68.setEditable(false);
        jTextArea68.setBackground(new java.awt.Color(153, 255, 255));
        jTextArea68.setColumns(20);
        jTextArea68.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jTextArea68.setRows(5);
        jTextArea68.setText("Ingles\n técnico");
        jTextArea68.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextArea68.setMinimumSize(new java.awt.Dimension(60, 11));
        jPanel2.add(jTextArea68);
        jTextArea68.setBounds(150, 30, 50, 80);

        jTextArea63.setEditable(false);
        jTextArea63.setBackground(new java.awt.Color(153, 255, 255));
        jTextArea63.setColumns(20);
        jTextArea63.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jTextArea63.setRows(5);
        jTextArea63.setText("Contabi\nlidad\nfinancie\nra");
        jTextArea63.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextArea63.setMinimumSize(new java.awt.Dimension(60, 11));
        jPanel2.add(jTextArea63);
        jTextArea63.setBounds(200, 360, 50, 80);

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel20.setText("4:20 a 5:00");
        jPanel2.add(jLabel20);
        jLabel20.setBounds(10, 440, 60, 13);

        jTextArea74.setEditable(false);
        jTextArea74.setBackground(new java.awt.Color(153, 255, 255));
        jTextArea74.setColumns(20);
        jTextArea74.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jTextArea74.setRows(5);
        jTextArea74.setText("Contabi\nlidad\nfinancie\nra");
        jTextArea74.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextArea74.setMinimumSize(new java.awt.Dimension(60, 11));
        jPanel2.add(jTextArea74);
        jTextArea74.setBounds(450, 140, 50, 80);

        jTextArea75.setEditable(false);
        jTextArea75.setBackground(new java.awt.Color(153, 255, 255));
        jTextArea75.setColumns(20);
        jTextArea75.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jTextArea75.setRows(5);
        jTextArea75.setText("Contabi\nlidad\nfinancie\nra");
        jTextArea75.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextArea75.setMinimumSize(new java.awt.Dimension(60, 11));
        jPanel2.add(jTextArea75);
        jTextArea75.setBounds(550, 30, 50, 80);

        jTextArea58.setEditable(false);
        jTextArea58.setBackground(new java.awt.Color(153, 255, 255));
        jTextArea58.setColumns(20);
        jTextArea58.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jTextArea58.setRows(5);
        jTextArea58.setText("Contex\nto\nlegal");
        jTextArea58.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextArea58.setMinimumSize(new java.awt.Dimension(60, 11));
        jPanel2.add(jTextArea58);
        jTextArea58.setBounds(150, 140, 50, 80);

        jTextArea76.setEditable(false);
        jTextArea76.setBackground(new java.awt.Color(153, 255, 255));
        jTextArea76.setColumns(20);
        jTextArea76.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jTextArea76.setRows(5);
        jTextArea76.setText("Contabi\nlidad\nfinancie\nra");
        jTextArea76.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextArea76.setMinimumSize(new java.awt.Dimension(60, 11));
        jPanel2.add(jTextArea76);
        jTextArea76.setBounds(300, 140, 50, 80);

        jTextArea62.setEditable(false);
        jTextArea62.setBackground(new java.awt.Color(153, 255, 255));
        jTextArea62.setColumns(20);
        jTextArea62.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jTextArea62.setRows(5);
        jTextArea62.setText("Contex\nto\nlegal");
        jTextArea62.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextArea62.setMinimumSize(new java.awt.Dimension(60, 11));
        jPanel2.add(jTextArea62);
        jTextArea62.setBounds(400, 250, 50, 80);

        jTextArea77.setEditable(false);
        jTextArea77.setBackground(new java.awt.Color(153, 255, 255));
        jTextArea77.setColumns(20);
        jTextArea77.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jTextArea77.setRows(5);
        jTextArea77.setText("Contabi\nlidad\nfinancie\nra");
        jTextArea77.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextArea77.setMinimumSize(new java.awt.Dimension(60, 11));
        jPanel2.add(jTextArea77);
        jTextArea77.setBounds(200, 250, 50, 80);

        jTextArea78.setEditable(false);
        jTextArea78.setBackground(new java.awt.Color(153, 255, 255));
        jTextArea78.setColumns(20);
        jTextArea78.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jTextArea78.setRows(5);
        jTextArea78.setText("Contabi\nlidad\nfinancie\nra");
        jTextArea78.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextArea78.setMinimumSize(new java.awt.Dimension(60, 11));
        jPanel2.add(jTextArea78);
        jTextArea78.setBounds(300, 30, 50, 80);

        jTextArea79.setEditable(false);
        jTextArea79.setBackground(new java.awt.Color(153, 255, 255));
        jTextArea79.setColumns(20);
        jTextArea79.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jTextArea79.setRows(5);
        jTextArea79.setText("Contabi\nlidad\nfinancie\nra");
        jTextArea79.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextArea79.setMinimumSize(new java.awt.Dimension(60, 11));
        jPanel2.add(jTextArea79);
        jTextArea79.setBounds(350, 30, 50, 80);

        jTextArea80.setEditable(false);
        jTextArea80.setBackground(new java.awt.Color(153, 255, 255));
        jTextArea80.setColumns(20);
        jTextArea80.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jTextArea80.setRows(5);
        jTextArea80.setText("Contabi\nlidad\nfinancie\nra");
        jTextArea80.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextArea80.setMinimumSize(new java.awt.Dimension(60, 11));
        jPanel2.add(jTextArea80);
        jTextArea80.setBounds(350, 140, 50, 80);

        jTextArea47.setEditable(false);
        jTextArea47.setBackground(new java.awt.Color(153, 255, 255));
        jTextArea47.setColumns(20);
        jTextArea47.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jTextArea47.setRows(5);
        jTextArea47.setText("Est.Sociales");
        jTextArea47.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.add(jTextArea47);
        jTextArea47.setBounds(300, 360, 100, 20);

        jTextArea81.setEditable(false);
        jTextArea81.setBackground(new java.awt.Color(153, 255, 255));
        jTextArea81.setColumns(20);
        jTextArea81.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jTextArea81.setRows(5);
        jTextArea81.setText("Contex\nto\nlegal");
        jTextArea81.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextArea81.setMinimumSize(new java.awt.Dimension(60, 11));
        jPanel2.add(jTextArea81);
        jTextArea81.setBounds(250, 250, 50, 80);

        jTextArea84.setEditable(false);
        jTextArea84.setBackground(new java.awt.Color(153, 255, 255));
        jTextArea84.setColumns(20);
        jTextArea84.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jTextArea84.setRows(5);
        jTextArea84.setText("Contabi\nlidad\nde\ncostos");
        jTextArea84.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextArea84.setMinimumSize(new java.awt.Dimension(60, 11));
        jPanel2.add(jTextArea84);
        jTextArea84.setBounds(500, 30, 50, 80);

        jTextArea85.setEditable(false);
        jTextArea85.setBackground(new java.awt.Color(153, 255, 255));
        jTextArea85.setColumns(20);
        jTextArea85.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jTextArea85.setRows(5);
        jTextArea85.setText("Contabi\nlidad\nfinancie\nra");
        jTextArea85.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextArea85.setMinimumSize(new java.awt.Dimension(60, 11));
        jPanel2.add(jTextArea85);
        jTextArea85.setBounds(450, 360, 50, 80);

        jTextArea86.setEditable(false);
        jTextArea86.setBackground(new java.awt.Color(153, 255, 255));
        jTextArea86.setColumns(20);
        jTextArea86.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jTextArea86.setRows(5);
        jTextArea86.setText("Contabi\nlidad\nfinancie\nra");
        jTextArea86.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextArea86.setMinimumSize(new java.awt.Dimension(60, 11));
        jPanel2.add(jTextArea86);
        jTextArea86.setBounds(450, 250, 50, 80);

        jTextArea87.setEditable(false);
        jTextArea87.setBackground(new java.awt.Color(153, 255, 255));
        jTextArea87.setColumns(20);
        jTextArea87.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jTextArea87.setRows(5);
        jTextArea87.setText("Contabi\nlidad\nfinancie\nra");
        jTextArea87.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextArea87.setMinimumSize(new java.awt.Dimension(60, 11));
        jPanel2.add(jTextArea87);
        jTextArea87.setBounds(450, 30, 50, 80);

        jTextArea88.setEditable(false);
        jTextArea88.setBackground(new java.awt.Color(153, 255, 255));
        jTextArea88.setColumns(20);
        jTextArea88.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jTextArea88.setRows(5);
        jTextArea88.setText("Contabi\nlidad\nfinancie\nra");
        jTextArea88.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextArea88.setMinimumSize(new java.awt.Dimension(60, 11));
        jPanel2.add(jTextArea88);
        jTextArea88.setBounds(450, 30, 50, 80);

        jTextArea89.setEditable(false);
        jTextArea89.setBackground(new java.awt.Color(153, 255, 255));
        jTextArea89.setColumns(20);
        jTextArea89.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jTextArea89.setRows(5);
        jTextArea89.setText("Contabi\nlidad\nfinancie\nra");
        jTextArea89.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextArea89.setMinimumSize(new java.awt.Dimension(60, 11));
        jPanel2.add(jTextArea89);
        jTextArea89.setBounds(100, 140, 50, 80);

        jTextArea90.setEditable(false);
        jTextArea90.setBackground(new java.awt.Color(153, 255, 255));
        jTextArea90.setColumns(20);
        jTextArea90.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jTextArea90.setRows(5);
        jTextArea90.setText("Contabi\nlidad\nfinancie\nra");
        jTextArea90.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextArea90.setMinimumSize(new java.awt.Dimension(60, 11));
        jPanel2.add(jTextArea90);
        jTextArea90.setBounds(550, 140, 50, 80);

        jTextArea91.setEditable(false);
        jTextArea91.setBackground(new java.awt.Color(153, 255, 255));
        jTextArea91.setColumns(20);
        jTextArea91.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jTextArea91.setRows(5);
        jTextArea91.setText("Contabi\nlidad\nfinancie\nra");
        jTextArea91.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextArea91.setMinimumSize(new java.awt.Dimension(60, 11));
        jPanel2.add(jTextArea91);
        jTextArea91.setBounds(100, 30, 50, 80);

        jTextArea93.setEditable(false);
        jTextArea93.setBackground(new java.awt.Color(153, 255, 255));
        jTextArea93.setColumns(20);
        jTextArea93.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jTextArea93.setRows(5);
        jTextArea93.setText("Contabi\nlidad\nfinancie\nra");
        jTextArea93.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextArea93.setMinimumSize(new java.awt.Dimension(60, 11));
        jPanel2.add(jTextArea93);
        jTextArea93.setBounds(400, 140, 50, 80);

        jTextArea94.setEditable(false);
        jTextArea94.setBackground(new java.awt.Color(153, 255, 255));
        jTextArea94.setColumns(20);
        jTextArea94.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jTextArea94.setRows(5);
        jTextArea94.setText("Contabi\nlidad\nde\ncostos");
        jTextArea94.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextArea94.setMinimumSize(new java.awt.Dimension(60, 11));
        jPanel2.add(jTextArea94);
        jTextArea94.setBounds(400, 30, 50, 80);

        jTextArea95.setEditable(false);
        jTextArea95.setBackground(new java.awt.Color(153, 255, 255));
        jTextArea95.setColumns(20);
        jTextArea95.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jTextArea95.setRows(5);
        jTextArea95.setText("Contabi\nlidad\nde\ncostos");
        jTextArea95.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextArea95.setMinimumSize(new java.awt.Dimension(60, 11));
        jPanel2.add(jTextArea95);
        jTextArea95.setBounds(500, 140, 50, 80);

        jTextArea96.setEditable(false);
        jTextArea96.setBackground(new java.awt.Color(153, 255, 255));
        jTextArea96.setColumns(20);
        jTextArea96.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jTextArea96.setRows(5);
        jTextArea96.setText("Contabi\nlidad\nde\ncostos");
        jTextArea96.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextArea96.setMinimumSize(new java.awt.Dimension(60, 11));
        jPanel2.add(jTextArea96);
        jTextArea96.setBounds(500, 140, 50, 80);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 690, 450);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 613, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 453, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Undecimo um = new Undecimo();
        um.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Lunes;
    private javax.swing.JLabel Lunes1;
    private javax.swing.JLabel Lunes2;
    private javax.swing.JLabel Lunes3;
    private javax.swing.JLabel Lunes4;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextArea jTextArea18;
    private javax.swing.JTextArea jTextArea20;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextArea jTextArea31;
    private javax.swing.JTextArea jTextArea32;
    private javax.swing.JTextArea jTextArea39;
    private javax.swing.JTextArea jTextArea40;
    private javax.swing.JTextArea jTextArea44;
    private javax.swing.JTextArea jTextArea45;
    private javax.swing.JTextArea jTextArea46;
    private javax.swing.JTextArea jTextArea47;
    private javax.swing.JTextArea jTextArea57;
    private javax.swing.JTextArea jTextArea58;
    private javax.swing.JTextArea jTextArea62;
    private javax.swing.JTextArea jTextArea63;
    private javax.swing.JTextArea jTextArea64;
    private javax.swing.JTextArea jTextArea68;
    private javax.swing.JTextArea jTextArea7;
    private javax.swing.JTextArea jTextArea74;
    private javax.swing.JTextArea jTextArea75;
    private javax.swing.JTextArea jTextArea76;
    private javax.swing.JTextArea jTextArea77;
    private javax.swing.JTextArea jTextArea78;
    private javax.swing.JTextArea jTextArea79;
    private javax.swing.JTextArea jTextArea8;
    private javax.swing.JTextArea jTextArea80;
    private javax.swing.JTextArea jTextArea81;
    private javax.swing.JTextArea jTextArea84;
    private javax.swing.JTextArea jTextArea85;
    private javax.swing.JTextArea jTextArea86;
    private javax.swing.JTextArea jTextArea87;
    private javax.swing.JTextArea jTextArea88;
    private javax.swing.JTextArea jTextArea89;
    private javax.swing.JTextArea jTextArea90;
    private javax.swing.JTextArea jTextArea91;
    private javax.swing.JTextArea jTextArea93;
    private javax.swing.JTextArea jTextArea94;
    private javax.swing.JTextArea jTextArea95;
    private javax.swing.JTextArea jTextArea96;
    // End of variables declaration//GEN-END:variables
}
