package Secciones;

import javax.swing.ImageIcon;

/**
 *
 * @author aarui
 */
public class OnceUno extends javax.swing.JFrame {

    /**
     * Creates new form OnceUno
     */
    public OnceUno() {
        initComponents();
        setLocationRelativeTo(null);
        ImageIcon ii;
        ii=new ImageIcon(this.getClass().getResource("/Imagenes/HORARIO.png"));
        this.setIconImage(ii.getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        Lunes = new javax.swing.JLabel();
        Lunes1 = new javax.swing.JLabel();
        Lunes2 = new javax.swing.JLabel();
        Lunes3 = new javax.swing.JLabel();
        Lunes4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextArea3 = new javax.swing.JTextArea();
        jTextArea24 = new javax.swing.JTextArea();
        jTextArea41 = new javax.swing.JTextArea();
        jTextArea43 = new javax.swing.JTextArea();
        jTextArea47 = new javax.swing.JTextArea();
        jTextArea33 = new javax.swing.JTextArea();
        jTextArea48 = new javax.swing.JTextArea();
        jTextArea51 = new javax.swing.JTextArea();
        jTextArea9 = new javax.swing.JTextArea();
        jTextArea36 = new javax.swing.JTextArea();
        jTextArea53 = new javax.swing.JTextArea();
        jTextArea55 = new javax.swing.JTextArea();
        jTextArea56 = new javax.swing.JTextArea();
        jTextArea58 = new javax.swing.JTextArea();
        jTextArea60 = new javax.swing.JTextArea();
        jTextArea78 = new javax.swing.JTextArea();
        jTextArea79 = new javax.swing.JTextArea();
        jTextArea80 = new javax.swing.JTextArea();
        jTextArea81 = new javax.swing.JTextArea();
        jTextArea62 = new javax.swing.JTextArea();
        jTextArea82 = new javax.swing.JTextArea();
        jTextArea83 = new javax.swing.JTextArea();
        jTextArea84 = new javax.swing.JTextArea();
        jTextArea85 = new javax.swing.JTextArea();
        jTextArea86 = new javax.swing.JTextArea();
        jTextArea87 = new javax.swing.JTextArea();
        jTextArea88 = new javax.swing.JTextArea();
        jTextArea89 = new javax.swing.JTextArea();
        jTextArea90 = new javax.swing.JTextArea();
        jTextArea91 = new javax.swing.JTextArea();
        jTextArea92 = new javax.swing.JTextArea();
        jTextArea93 = new javax.swing.JTextArea();
        jTextArea94 = new javax.swing.JTextArea();
        jTextArea34 = new javax.swing.JTextArea();
        jTextArea21 = new javax.swing.JTextArea();
        jTextArea19 = new javax.swing.JTextArea();
        jTextArea10 = new javax.swing.JTextArea();
        jTextArea4 = new javax.swing.JTextArea();
        jTextArea7 = new javax.swing.JTextArea();
        jTextArea18 = new javax.swing.JTextArea();
        jTextArea20 = new javax.swing.JTextArea();
        jTextArea31 = new javax.swing.JTextArea();
        jTextArea23 = new javax.swing.JTextArea();
        jTextArea39 = new javax.swing.JTextArea();
        jTextArea40 = new javax.swing.JTextArea();
        jTextArea44 = new javax.swing.JTextArea();
        jTextArea32 = new javax.swing.JTextArea();
        jTextArea45 = new javax.swing.JTextArea();
        jTextArea46 = new javax.swing.JTextArea();
        jTextArea8 = new javax.swing.JTextArea();
        jTextArea35 = new javax.swing.JTextArea();
        jTextArea49 = new javax.swing.JTextArea();
        jTextArea50 = new javax.swing.JTextArea();
        jTextArea54 = new javax.swing.JTextArea();
        jTextArea57 = new javax.swing.JTextArea();
        jTextArea52 = new javax.swing.JTextArea();
        jTextArea64 = new javax.swing.JTextArea();
        jTextArea65 = new javax.swing.JTextArea();
        jTextArea66 = new javax.swing.JTextArea();
        jTextArea68 = new javax.swing.JTextArea();
        jTextArea59 = new javax.swing.JTextArea();
        jTextArea70 = new javax.swing.JTextArea();
        jTextArea71 = new javax.swing.JTextArea();
        jTextArea61 = new javax.swing.JTextArea();
        jTextArea63 = new javax.swing.JTextArea();
        jTextArea72 = new javax.swing.JTextArea();
        jTextArea73 = new javax.swing.JTextArea();
        jTextArea42 = new javax.swing.JTextArea();
        jTextArea67 = new javax.swing.JTextArea();
        jTextArea69 = new javax.swing.JTextArea();
        jTextArea74 = new javax.swing.JTextArea();
        jTextArea75 = new javax.swing.JTextArea();
        jTextArea76 = new javax.swing.JTextArea();
        jTextArea77 = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));
        jPanel2.setLayout(null);

        Lunes.setBackground(new java.awt.Color(153, 204, 255));
        Lunes.setText("Martes");
        Lunes.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Lunes.setInheritsPopupMenu(false);
        Lunes.setOpaque(true);
        jPanel2.add(Lunes);
        Lunes.setBounds(200, 10, 100, 20);

        Lunes1.setBackground(new java.awt.Color(153, 204, 255));
        Lunes1.setText("Viernes");
        Lunes1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Lunes1.setInheritsPopupMenu(false);
        Lunes1.setOpaque(true);
        jPanel2.add(Lunes1);
        Lunes1.setBounds(500, 10, 100, 20);

        Lunes2.setBackground(new java.awt.Color(153, 204, 255));
        Lunes2.setText("Jueves");
        Lunes2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Lunes2.setInheritsPopupMenu(false);
        Lunes2.setOpaque(true);
        jPanel2.add(Lunes2);
        Lunes2.setBounds(400, 10, 100, 20);

        Lunes3.setBackground(new java.awt.Color(153, 204, 255));
        Lunes3.setText("Miercoles");
        Lunes3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Lunes3.setInheritsPopupMenu(false);
        Lunes3.setOpaque(true);
        jPanel2.add(Lunes3);
        Lunes3.setBounds(300, 10, 100, 20);

        Lunes4.setBackground(new java.awt.Color(153, 204, 255));
        Lunes4.setText("Lunes");
        Lunes4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Lunes4.setInheritsPopupMenu(false);
        Lunes4.setOpaque(true);
        jPanel2.add(Lunes4);
        Lunes4.setBounds(100, 10, 100, 20);

        jLabel5.setBackground(new java.awt.Color(102, 153, 255));
        jLabel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLabel5.setOpaque(true);
        jPanel2.add(jLabel5);
        jLabel5.setBounds(100, 340, 500, 30);

        jLabel6.setBackground(new java.awt.Color(102, 153, 255));
        jLabel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLabel6.setOpaque(true);
        jPanel2.add(jLabel6);
        jLabel6.setBounds(100, 230, 500, 30);

        jLabel7.setBackground(new java.awt.Color(102, 153, 255));
        jLabel7.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLabel7.setOpaque(true);
        jPanel2.add(jLabel7);
        jLabel7.setBounds(100, 120, 500, 30);

        jTextArea3.setEditable(false);
        jTextArea3.setBackground(new java.awt.Color(153, 255, 255));
        jTextArea3.setColumns(20);
        jTextArea3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jTextArea3.setRows(5);
        jTextArea3.setText("Matemáticas");
        jTextArea3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.add(jTextArea3);
        jTextArea3.setBounds(200, 150, 100, 80);

        jTextArea24.setEditable(false);
        jTextArea24.setBackground(new java.awt.Color(153, 255, 255));
        jTextArea24.setColumns(20);
        jTextArea24.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jTextArea24.setRows(5);
        jTextArea24.setText("Comu\nnicacion ");
        jTextArea24.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextArea24.setMinimumSize(new java.awt.Dimension(60, 11));
        jPanel2.add(jTextArea24);
        jTextArea24.setBounds(100, 150, 50, 80);

        jTextArea41.setEditable(false);
        jTextArea41.setBackground(new java.awt.Color(153, 255, 255));
        jTextArea41.setColumns(20);
        jTextArea41.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jTextArea41.setRows(5);
        jTextArea41.setText("Educ.Física");
        jTextArea41.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.add(jTextArea41);
        jTextArea41.setBounds(100, 370, 100, 30);

        jTextArea43.setEditable(false);
        jTextArea43.setBackground(new java.awt.Color(153, 255, 255));
        jTextArea43.setColumns(20);
        jTextArea43.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jTextArea43.setRows(5);
        jTextArea43.setText("Educ.Religiosa");
        jTextArea43.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.add(jTextArea43);
        jTextArea43.setBounds(100, 420, 100, 30);

        jTextArea47.setEditable(false);
        jTextArea47.setBackground(new java.awt.Color(153, 255, 255));
        jTextArea47.setColumns(20);
        jTextArea47.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jTextArea47.setRows(5);
        jTextArea47.setText("Cívica");
        jTextArea47.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.add(jTextArea47);
        jTextArea47.setBounds(100, 400, 100, 20);

        jTextArea33.setEditable(false);
        jTextArea33.setBackground(new java.awt.Color(153, 255, 255));
        jTextArea33.setColumns(20);
        jTextArea33.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jTextArea33.setRows(5);
        jTextArea33.setText("Guía");
        jTextArea33.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.add(jTextArea33);
        jTextArea33.setBounds(300, 100, 100, 20);

        jTextArea48.setEditable(false);
        jTextArea48.setBackground(new java.awt.Color(153, 255, 255));
        jTextArea48.setColumns(20);
        jTextArea48.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jTextArea48.setRows(5);
        jTextArea48.setText("Psicología");
        jTextArea48.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.add(jTextArea48);
        jTextArea48.setBounds(300, 70, 100, 30);

        jTextArea51.setEditable(false);
        jTextArea51.setBackground(new java.awt.Color(153, 255, 255));
        jTextArea51.setColumns(20);
        jTextArea51.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jTextArea51.setRows(5);
        jTextArea51.setText("Est.Sociales");
        jTextArea51.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.add(jTextArea51);
        jTextArea51.setBounds(100, 260, 100, 50);

        jTextArea9.setEditable(false);
        jTextArea9.setBackground(new java.awt.Color(153, 255, 255));
        jTextArea9.setColumns(20);
        jTextArea9.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jTextArea9.setRows(5);
        jTextArea9.setText("Quimíca");
        jTextArea9.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.add(jTextArea9);
        jTextArea9.setBounds(300, 260, 100, 80);

        jTextArea36.setEditable(false);
        jTextArea36.setBackground(new java.awt.Color(153, 255, 255));
        jTextArea36.setColumns(20);
        jTextArea36.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jTextArea36.setRows(5);
        jTextArea36.setText("Comu\nnicacion ");
        jTextArea36.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextArea36.setMinimumSize(new java.awt.Dimension(60, 11));
        jPanel2.add(jTextArea36);
        jTextArea36.setBounds(100, 40, 50, 80);

        jTextArea53.setEditable(false);
        jTextArea53.setBackground(new java.awt.Color(153, 255, 255));
        jTextArea53.setColumns(20);
        jTextArea53.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jTextArea53.setRows(5);
        jTextArea53.setText("Ingles \ntécnico");
        jTextArea53.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextArea53.setMinimumSize(new java.awt.Dimension(60, 11));
        jPanel2.add(jTextArea53);
        jTextArea53.setBounds(200, 370, 50, 80);

        jTextArea55.setEditable(false);
        jTextArea55.setBackground(new java.awt.Color(153, 255, 255));
        jTextArea55.setColumns(20);
        jTextArea55.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jTextArea55.setRows(5);
        jTextArea55.setText("Comu\nnicacion ");
        jTextArea55.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextArea55.setMinimumSize(new java.awt.Dimension(60, 11));
        jPanel2.add(jTextArea55);
        jTextArea55.setBounds(400, 260, 50, 80);

        jTextArea56.setEditable(false);
        jTextArea56.setBackground(new java.awt.Color(153, 255, 255));
        jTextArea56.setColumns(20);
        jTextArea56.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jTextArea56.setRows(5);
        jTextArea56.setText("Gestion\nempre\nsarial");
        jTextArea56.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextArea56.setMinimumSize(new java.awt.Dimension(60, 11));
        jPanel2.add(jTextArea56);
        jTextArea56.setBounds(250, 370, 50, 80);

        jTextArea58.setEditable(false);
        jTextArea58.setBackground(new java.awt.Color(153, 255, 255));
        jTextArea58.setColumns(20);
        jTextArea58.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jTextArea58.setRows(5);
        jTextArea58.setText("Destre\nzas");
        jTextArea58.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextArea58.setMinimumSize(new java.awt.Dimension(60, 11));
        jPanel2.add(jTextArea58);
        jTextArea58.setBounds(550, 370, 50, 80);

        jTextArea60.setEditable(false);
        jTextArea60.setBackground(new java.awt.Color(153, 255, 255));
        jTextArea60.setColumns(20);
        jTextArea60.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jTextArea60.setRows(5);
        jTextArea60.setText("Ingles \ntécnico");
        jTextArea60.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextArea60.setMinimumSize(new java.awt.Dimension(60, 11));
        jPanel2.add(jTextArea60);
        jTextArea60.setBounds(450, 150, 50, 80);

        jTextArea78.setEditable(false);
        jTextArea78.setBackground(new java.awt.Color(153, 255, 255));
        jTextArea78.setColumns(20);
        jTextArea78.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jTextArea78.setRows(5);
        jTextArea78.setText("Ingles \ntécnico");
        jTextArea78.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextArea78.setMinimumSize(new java.awt.Dimension(60, 11));
        jPanel2.add(jTextArea78);
        jTextArea78.setBounds(450, 40, 50, 80);

        jTextArea79.setEditable(false);
        jTextArea79.setBackground(new java.awt.Color(153, 255, 255));
        jTextArea79.setColumns(20);
        jTextArea79.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jTextArea79.setRows(5);
        jTextArea79.setText("Destre\nzas");
        jTextArea79.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextArea79.setMinimumSize(new java.awt.Dimension(60, 11));
        jPanel2.add(jTextArea79);
        jTextArea79.setBounds(400, 150, 50, 80);

        jTextArea80.setEditable(false);
        jTextArea80.setBackground(new java.awt.Color(153, 255, 255));
        jTextArea80.setColumns(20);
        jTextArea80.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jTextArea80.setRows(5);
        jTextArea80.setText("Comu\nnicacion ");
        jTextArea80.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextArea80.setMinimumSize(new java.awt.Dimension(60, 11));
        jPanel2.add(jTextArea80);
        jTextArea80.setBounds(450, 370, 50, 80);

        jTextArea81.setEditable(false);
        jTextArea81.setBackground(new java.awt.Color(153, 255, 255));
        jTextArea81.setColumns(20);
        jTextArea81.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jTextArea81.setRows(5);
        jTextArea81.setText("Ingles\n técnico");
        jTextArea81.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextArea81.setMinimumSize(new java.awt.Dimension(60, 11));
        jPanel2.add(jTextArea81);
        jTextArea81.setBounds(200, 260, 50, 80);

        jTextArea62.setEditable(false);
        jTextArea62.setBackground(new java.awt.Color(153, 255, 255));
        jTextArea62.setColumns(20);
        jTextArea62.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jTextArea62.setRows(5);
        jTextArea62.setText("Gestion\nempre\nsarial");
        jTextArea62.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextArea62.setMinimumSize(new java.awt.Dimension(60, 11));
        jPanel2.add(jTextArea62);
        jTextArea62.setBounds(500, 370, 50, 80);

        jTextArea82.setEditable(false);
        jTextArea82.setBackground(new java.awt.Color(153, 255, 255));
        jTextArea82.setColumns(20);
        jTextArea82.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jTextArea82.setRows(5);
        jTextArea82.setText("Comu\nnicacion ");
        jTextArea82.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextArea82.setMinimumSize(new java.awt.Dimension(60, 11));
        jPanel2.add(jTextArea82);
        jTextArea82.setBounds(400, 370, 50, 80);

        jTextArea83.setEditable(false);
        jTextArea83.setBackground(new java.awt.Color(153, 255, 255));
        jTextArea83.setColumns(20);
        jTextArea83.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jTextArea83.setRows(5);
        jTextArea83.setText("Comu\nnicacion ");
        jTextArea83.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextArea83.setMinimumSize(new java.awt.Dimension(60, 11));
        jPanel2.add(jTextArea83);
        jTextArea83.setBounds(500, 150, 50, 80);

        jTextArea84.setEditable(false);
        jTextArea84.setBackground(new java.awt.Color(153, 255, 255));
        jTextArea84.setColumns(20);
        jTextArea84.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jTextArea84.setRows(5);
        jTextArea84.setText("Destre\nzas");
        jTextArea84.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextArea84.setMinimumSize(new java.awt.Dimension(60, 11));
        jPanel2.add(jTextArea84);
        jTextArea84.setBounds(400, 40, 50, 80);

        jTextArea85.setEditable(false);
        jTextArea85.setBackground(new java.awt.Color(153, 255, 255));
        jTextArea85.setColumns(20);
        jTextArea85.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jTextArea85.setRows(5);
        jTextArea85.setText("Destre\nzas");
        jTextArea85.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextArea85.setMinimumSize(new java.awt.Dimension(60, 11));
        jPanel2.add(jTextArea85);
        jTextArea85.setBounds(550, 260, 50, 80);

        jTextArea86.setEditable(false);
        jTextArea86.setBackground(new java.awt.Color(153, 255, 255));
        jTextArea86.setColumns(20);
        jTextArea86.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jTextArea86.setRows(5);
        jTextArea86.setText("Gestion\nempresarial");
        jTextArea86.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextArea86.setMinimumSize(new java.awt.Dimension(60, 11));
        jPanel2.add(jTextArea86);
        jTextArea86.setBounds(250, 260, 50, 80);

        jTextArea87.setEditable(false);
        jTextArea87.setBackground(new java.awt.Color(153, 255, 255));
        jTextArea87.setColumns(20);
        jTextArea87.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jTextArea87.setRows(5);
        jTextArea87.setText("Gestion\nempre\nsarial");
        jTextArea87.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextArea87.setMinimumSize(new java.awt.Dimension(60, 11));
        jPanel2.add(jTextArea87);
        jTextArea87.setBounds(150, 150, 50, 80);

        jTextArea88.setEditable(false);
        jTextArea88.setBackground(new java.awt.Color(153, 255, 255));
        jTextArea88.setColumns(20);
        jTextArea88.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jTextArea88.setRows(5);
        jTextArea88.setText("Educ.Física");
        jTextArea88.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.add(jTextArea88);
        jTextArea88.setBounds(100, 310, 100, 30);

        jTextArea89.setEditable(false);
        jTextArea89.setBackground(new java.awt.Color(153, 255, 255));
        jTextArea89.setColumns(20);
        jTextArea89.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jTextArea89.setRows(5);
        jTextArea89.setText("Gestion\nempre\nsarial");
        jTextArea89.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextArea89.setMinimumSize(new java.awt.Dimension(60, 11));
        jPanel2.add(jTextArea89);
        jTextArea89.setBounds(150, 40, 50, 80);

        jTextArea90.setEditable(false);
        jTextArea90.setBackground(new java.awt.Color(153, 255, 255));
        jTextArea90.setColumns(20);
        jTextArea90.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jTextArea90.setRows(5);
        jTextArea90.setText("Gestion\nempre\nsarial");
        jTextArea90.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextArea90.setMinimumSize(new java.awt.Dimension(60, 11));
        jPanel2.add(jTextArea90);
        jTextArea90.setBounds(550, 40, 50, 80);

        jTextArea91.setEditable(false);
        jTextArea91.setBackground(new java.awt.Color(153, 255, 255));
        jTextArea91.setColumns(20);
        jTextArea91.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jTextArea91.setRows(5);
        jTextArea91.setText("Comu\nnicacion ");
        jTextArea91.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextArea91.setMinimumSize(new java.awt.Dimension(60, 11));
        jPanel2.add(jTextArea91);
        jTextArea91.setBounds(450, 260, 50, 80);

        jTextArea92.setEditable(false);
        jTextArea92.setBackground(new java.awt.Color(153, 255, 255));
        jTextArea92.setColumns(20);
        jTextArea92.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jTextArea92.setRows(5);
        jTextArea92.setText("Comu\nnicacion ");
        jTextArea92.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextArea92.setMinimumSize(new java.awt.Dimension(60, 11));
        jPanel2.add(jTextArea92);
        jTextArea92.setBounds(500, 40, 50, 80);

        jTextArea93.setEditable(false);
        jTextArea93.setBackground(new java.awt.Color(153, 255, 255));
        jTextArea93.setColumns(20);
        jTextArea93.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jTextArea93.setRows(5);
        jTextArea93.setText("Gestion\nempre\nsarial");
        jTextArea93.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextArea93.setMinimumSize(new java.awt.Dimension(60, 11));
        jPanel2.add(jTextArea93);
        jTextArea93.setBounds(550, 150, 50, 80);

        jTextArea94.setEditable(false);
        jTextArea94.setBackground(new java.awt.Color(153, 255, 255));
        jTextArea94.setColumns(20);
        jTextArea94.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jTextArea94.setRows(5);
        jTextArea94.setText("Gestion\nempre\nsarial");
        jTextArea94.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextArea94.setMinimumSize(new java.awt.Dimension(60, 11));
        jPanel2.add(jTextArea94);
        jTextArea94.setBounds(500, 260, 50, 80);

        jTextArea34.setEditable(false);
        jTextArea34.setBackground(new java.awt.Color(153, 255, 255));
        jTextArea34.setColumns(20);
        jTextArea34.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jTextArea34.setRows(5);
        jTextArea34.setText("Educ.Músical");
        jTextArea34.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.add(jTextArea34);
        jTextArea34.setBounds(300, 40, 100, 30);

        jTextArea21.setEditable(false);
        jTextArea21.setBackground(new java.awt.Color(153, 255, 255));
        jTextArea21.setColumns(20);
        jTextArea21.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jTextArea21.setRows(5);
        jTextArea21.setText("Inglés");
        jTextArea21.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.add(jTextArea21);
        jTextArea21.setBounds(300, 150, 100, 80);

        jTextArea19.setEditable(false);
        jTextArea19.setBackground(new java.awt.Color(153, 255, 255));
        jTextArea19.setColumns(20);
        jTextArea19.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jTextArea19.setRows(5);
        jTextArea19.setText("Español");
        jTextArea19.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.add(jTextArea19);
        jTextArea19.setBounds(200, 40, 100, 80);

        jTextArea10.setEditable(false);
        jTextArea10.setBackground(new java.awt.Color(153, 255, 255));
        jTextArea10.setColumns(20);
        jTextArea10.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jTextArea10.setRows(5);
        jTextArea10.setText("Biología");
        jTextArea10.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.add(jTextArea10);
        jTextArea10.setBounds(300, 370, 100, 80);

        jTextArea4.setEditable(false);
        jTextArea4.setBackground(new java.awt.Color(153, 255, 255));
        jTextArea4.setColumns(20);
        jTextArea4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jTextArea4.setRows(5);
        jTextArea4.setText("Matemáticas");
        jTextArea4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.add(jTextArea4);
        jTextArea4.setBounds(200, 150, 100, 80);

        jTextArea7.setEditable(false);
        jTextArea7.setBackground(new java.awt.Color(153, 255, 255));
        jTextArea7.setColumns(20);
        jTextArea7.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jTextArea7.setRows(5);
        jTextArea7.setText("Biología");
        jTextArea7.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.add(jTextArea7);
        jTextArea7.setBounds(300, 370, 100, 80);

        jTextArea18.setEditable(false);
        jTextArea18.setBackground(new java.awt.Color(153, 255, 255));
        jTextArea18.setColumns(20);
        jTextArea18.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jTextArea18.setRows(5);
        jTextArea18.setText("Español");
        jTextArea18.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.add(jTextArea18);
        jTextArea18.setBounds(200, 40, 100, 80);

        jTextArea20.setEditable(false);
        jTextArea20.setBackground(new java.awt.Color(153, 255, 255));
        jTextArea20.setColumns(20);
        jTextArea20.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jTextArea20.setRows(5);
        jTextArea20.setText("Inglés");
        jTextArea20.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.add(jTextArea20);
        jTextArea20.setBounds(300, 150, 100, 80);

        jTextArea31.setEditable(false);
        jTextArea31.setBackground(new java.awt.Color(153, 255, 255));
        jTextArea31.setColumns(20);
        jTextArea31.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jTextArea31.setRows(5);
        jTextArea31.setText("Educ.Músical");
        jTextArea31.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.add(jTextArea31);
        jTextArea31.setBounds(300, 40, 100, 30);

        jTextArea23.setEditable(false);
        jTextArea23.setBackground(new java.awt.Color(153, 255, 255));
        jTextArea23.setColumns(20);
        jTextArea23.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jTextArea23.setRows(5);
        jTextArea23.setText("Comu\nnicacion ");
        jTextArea23.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextArea23.setMinimumSize(new java.awt.Dimension(60, 11));
        jPanel2.add(jTextArea23);
        jTextArea23.setBounds(100, 150, 50, 80);

        jTextArea39.setEditable(false);
        jTextArea39.setBackground(new java.awt.Color(153, 255, 255));
        jTextArea39.setColumns(20);
        jTextArea39.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jTextArea39.setRows(5);
        jTextArea39.setText("Educ.Física");
        jTextArea39.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.add(jTextArea39);
        jTextArea39.setBounds(100, 370, 100, 30);

        jTextArea40.setEditable(false);
        jTextArea40.setBackground(new java.awt.Color(153, 255, 255));
        jTextArea40.setColumns(20);
        jTextArea40.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jTextArea40.setRows(5);
        jTextArea40.setText("Educ.Religiosa");
        jTextArea40.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.add(jTextArea40);
        jTextArea40.setBounds(100, 420, 100, 30);

        jTextArea44.setEditable(false);
        jTextArea44.setBackground(new java.awt.Color(153, 255, 255));
        jTextArea44.setColumns(20);
        jTextArea44.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jTextArea44.setRows(5);
        jTextArea44.setText("Cívica");
        jTextArea44.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.add(jTextArea44);
        jTextArea44.setBounds(100, 400, 100, 20);

        jTextArea32.setEditable(false);
        jTextArea32.setBackground(new java.awt.Color(153, 255, 255));
        jTextArea32.setColumns(20);
        jTextArea32.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jTextArea32.setRows(5);
        jTextArea32.setText("Guía");
        jTextArea32.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.add(jTextArea32);
        jTextArea32.setBounds(300, 100, 100, 20);

        jTextArea45.setEditable(false);
        jTextArea45.setBackground(new java.awt.Color(153, 255, 255));
        jTextArea45.setColumns(20);
        jTextArea45.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jTextArea45.setRows(5);
        jTextArea45.setText("Psicología");
        jTextArea45.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.add(jTextArea45);
        jTextArea45.setBounds(300, 70, 100, 30);

        jTextArea46.setEditable(false);
        jTextArea46.setBackground(new java.awt.Color(153, 255, 255));
        jTextArea46.setColumns(20);
        jTextArea46.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jTextArea46.setRows(5);
        jTextArea46.setText("Est.Sociales");
        jTextArea46.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.add(jTextArea46);
        jTextArea46.setBounds(100, 260, 100, 50);

        jTextArea8.setEditable(false);
        jTextArea8.setBackground(new java.awt.Color(153, 255, 255));
        jTextArea8.setColumns(20);
        jTextArea8.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jTextArea8.setRows(5);
        jTextArea8.setText("Quimíca");
        jTextArea8.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.add(jTextArea8);
        jTextArea8.setBounds(300, 260, 100, 80);

        jTextArea35.setEditable(false);
        jTextArea35.setBackground(new java.awt.Color(153, 255, 255));
        jTextArea35.setColumns(20);
        jTextArea35.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jTextArea35.setRows(5);
        jTextArea35.setText("Comu\nnicacion ");
        jTextArea35.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextArea35.setMinimumSize(new java.awt.Dimension(60, 11));
        jPanel2.add(jTextArea35);
        jTextArea35.setBounds(100, 40, 50, 80);

        jTextArea49.setEditable(false);
        jTextArea49.setBackground(new java.awt.Color(153, 255, 255));
        jTextArea49.setColumns(20);
        jTextArea49.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jTextArea49.setRows(5);
        jTextArea49.setText("Ingles \ntécnico");
        jTextArea49.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextArea49.setMinimumSize(new java.awt.Dimension(60, 11));
        jPanel2.add(jTextArea49);
        jTextArea49.setBounds(200, 370, 50, 80);

        jTextArea50.setEditable(false);
        jTextArea50.setBackground(new java.awt.Color(153, 255, 255));
        jTextArea50.setColumns(20);
        jTextArea50.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jTextArea50.setRows(5);
        jTextArea50.setText("Comu\nnicacion ");
        jTextArea50.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextArea50.setMinimumSize(new java.awt.Dimension(60, 11));
        jPanel2.add(jTextArea50);
        jTextArea50.setBounds(400, 260, 50, 80);

        jTextArea54.setEditable(false);
        jTextArea54.setBackground(new java.awt.Color(153, 255, 255));
        jTextArea54.setColumns(20);
        jTextArea54.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jTextArea54.setRows(5);
        jTextArea54.setText("Gestion\nempre\nsarial");
        jTextArea54.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextArea54.setMinimumSize(new java.awt.Dimension(60, 11));
        jPanel2.add(jTextArea54);
        jTextArea54.setBounds(250, 370, 50, 80);

        jTextArea57.setEditable(false);
        jTextArea57.setBackground(new java.awt.Color(153, 255, 255));
        jTextArea57.setColumns(20);
        jTextArea57.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jTextArea57.setRows(5);
        jTextArea57.setText("Destre\nzas");
        jTextArea57.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextArea57.setMinimumSize(new java.awt.Dimension(60, 11));
        jPanel2.add(jTextArea57);
        jTextArea57.setBounds(550, 370, 50, 80);

        jTextArea52.setEditable(false);
        jTextArea52.setBackground(new java.awt.Color(153, 255, 255));
        jTextArea52.setColumns(20);
        jTextArea52.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jTextArea52.setRows(5);
        jTextArea52.setText("Ingles \ntécnico");
        jTextArea52.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextArea52.setMinimumSize(new java.awt.Dimension(60, 11));
        jPanel2.add(jTextArea52);
        jTextArea52.setBounds(450, 150, 50, 80);

        jTextArea64.setEditable(false);
        jTextArea64.setBackground(new java.awt.Color(153, 255, 255));
        jTextArea64.setColumns(20);
        jTextArea64.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jTextArea64.setRows(5);
        jTextArea64.setText("Ingles \ntécnico");
        jTextArea64.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextArea64.setMinimumSize(new java.awt.Dimension(60, 11));
        jPanel2.add(jTextArea64);
        jTextArea64.setBounds(450, 40, 50, 80);

        jTextArea65.setEditable(false);
        jTextArea65.setBackground(new java.awt.Color(153, 255, 255));
        jTextArea65.setColumns(20);
        jTextArea65.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jTextArea65.setRows(5);
        jTextArea65.setText("Destre\nzas");
        jTextArea65.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextArea65.setMinimumSize(new java.awt.Dimension(60, 11));
        jPanel2.add(jTextArea65);
        jTextArea65.setBounds(400, 150, 50, 80);

        jTextArea66.setEditable(false);
        jTextArea66.setBackground(new java.awt.Color(153, 255, 255));
        jTextArea66.setColumns(20);
        jTextArea66.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jTextArea66.setRows(5);
        jTextArea66.setText("Comu\nnicacion ");
        jTextArea66.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextArea66.setMinimumSize(new java.awt.Dimension(60, 11));
        jPanel2.add(jTextArea66);
        jTextArea66.setBounds(450, 370, 50, 80);

        jTextArea68.setEditable(false);
        jTextArea68.setBackground(new java.awt.Color(153, 255, 255));
        jTextArea68.setColumns(20);
        jTextArea68.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jTextArea68.setRows(5);
        jTextArea68.setText("Ingles\n técnico");
        jTextArea68.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextArea68.setMinimumSize(new java.awt.Dimension(60, 11));
        jPanel2.add(jTextArea68);
        jTextArea68.setBounds(200, 260, 50, 80);

        jTextArea59.setEditable(false);
        jTextArea59.setBackground(new java.awt.Color(153, 255, 255));
        jTextArea59.setColumns(20);
        jTextArea59.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jTextArea59.setRows(5);
        jTextArea59.setText("Gestion\nempre\nsarial");
        jTextArea59.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextArea59.setMinimumSize(new java.awt.Dimension(60, 11));
        jPanel2.add(jTextArea59);
        jTextArea59.setBounds(500, 370, 50, 80);

        jTextArea70.setEditable(false);
        jTextArea70.setBackground(new java.awt.Color(153, 255, 255));
        jTextArea70.setColumns(20);
        jTextArea70.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jTextArea70.setRows(5);
        jTextArea70.setText("Comu\nnicacion ");
        jTextArea70.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextArea70.setMinimumSize(new java.awt.Dimension(60, 11));
        jPanel2.add(jTextArea70);
        jTextArea70.setBounds(400, 370, 50, 80);

        jTextArea71.setEditable(false);
        jTextArea71.setBackground(new java.awt.Color(153, 255, 255));
        jTextArea71.setColumns(20);
        jTextArea71.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jTextArea71.setRows(5);
        jTextArea71.setText("Comu\nnicacion ");
        jTextArea71.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextArea71.setMinimumSize(new java.awt.Dimension(60, 11));
        jPanel2.add(jTextArea71);
        jTextArea71.setBounds(500, 150, 50, 80);

        jTextArea61.setEditable(false);
        jTextArea61.setBackground(new java.awt.Color(153, 255, 255));
        jTextArea61.setColumns(20);
        jTextArea61.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jTextArea61.setRows(5);
        jTextArea61.setText("Destre\nzas");
        jTextArea61.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextArea61.setMinimumSize(new java.awt.Dimension(60, 11));
        jPanel2.add(jTextArea61);
        jTextArea61.setBounds(400, 40, 50, 80);

        jTextArea63.setEditable(false);
        jTextArea63.setBackground(new java.awt.Color(153, 255, 255));
        jTextArea63.setColumns(20);
        jTextArea63.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jTextArea63.setRows(5);
        jTextArea63.setText("Destre\nzas");
        jTextArea63.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextArea63.setMinimumSize(new java.awt.Dimension(60, 11));
        jPanel2.add(jTextArea63);
        jTextArea63.setBounds(550, 260, 50, 80);

        jTextArea72.setEditable(false);
        jTextArea72.setBackground(new java.awt.Color(153, 255, 255));
        jTextArea72.setColumns(20);
        jTextArea72.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jTextArea72.setRows(5);
        jTextArea72.setText("Gestion\nempresarial");
        jTextArea72.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextArea72.setMinimumSize(new java.awt.Dimension(60, 11));
        jPanel2.add(jTextArea72);
        jTextArea72.setBounds(250, 260, 50, 80);

        jTextArea73.setEditable(false);
        jTextArea73.setBackground(new java.awt.Color(153, 255, 255));
        jTextArea73.setColumns(20);
        jTextArea73.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jTextArea73.setRows(5);
        jTextArea73.setText("Gestion\nempre\nsarial");
        jTextArea73.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextArea73.setMinimumSize(new java.awt.Dimension(60, 11));
        jPanel2.add(jTextArea73);
        jTextArea73.setBounds(150, 150, 50, 80);

        jTextArea42.setEditable(false);
        jTextArea42.setBackground(new java.awt.Color(153, 255, 255));
        jTextArea42.setColumns(20);
        jTextArea42.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jTextArea42.setRows(5);
        jTextArea42.setText("Educ.Física");
        jTextArea42.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.add(jTextArea42);
        jTextArea42.setBounds(100, 310, 100, 30);

        jTextArea67.setEditable(false);
        jTextArea67.setBackground(new java.awt.Color(153, 255, 255));
        jTextArea67.setColumns(20);
        jTextArea67.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jTextArea67.setRows(5);
        jTextArea67.setText("Gestion\nempre\nsarial");
        jTextArea67.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextArea67.setMinimumSize(new java.awt.Dimension(60, 11));
        jPanel2.add(jTextArea67);
        jTextArea67.setBounds(150, 40, 50, 80);

        jTextArea69.setEditable(false);
        jTextArea69.setBackground(new java.awt.Color(153, 255, 255));
        jTextArea69.setColumns(20);
        jTextArea69.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jTextArea69.setRows(5);
        jTextArea69.setText("Gestion\nempre\nsarial");
        jTextArea69.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextArea69.setMinimumSize(new java.awt.Dimension(60, 11));
        jPanel2.add(jTextArea69);
        jTextArea69.setBounds(550, 40, 50, 80);

        jTextArea74.setEditable(false);
        jTextArea74.setBackground(new java.awt.Color(153, 255, 255));
        jTextArea74.setColumns(20);
        jTextArea74.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jTextArea74.setRows(5);
        jTextArea74.setText("Comu\nnicacion ");
        jTextArea74.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextArea74.setMinimumSize(new java.awt.Dimension(60, 11));
        jPanel2.add(jTextArea74);
        jTextArea74.setBounds(450, 260, 50, 80);

        jTextArea75.setEditable(false);
        jTextArea75.setBackground(new java.awt.Color(153, 255, 255));
        jTextArea75.setColumns(20);
        jTextArea75.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jTextArea75.setRows(5);
        jTextArea75.setText("Comu\nnicacion ");
        jTextArea75.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextArea75.setMinimumSize(new java.awt.Dimension(60, 11));
        jPanel2.add(jTextArea75);
        jTextArea75.setBounds(500, 40, 50, 80);

        jTextArea76.setEditable(false);
        jTextArea76.setBackground(new java.awt.Color(153, 255, 255));
        jTextArea76.setColumns(20);
        jTextArea76.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jTextArea76.setRows(5);
        jTextArea76.setText("Gestion\nempre\nsarial");
        jTextArea76.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextArea76.setMinimumSize(new java.awt.Dimension(60, 11));
        jPanel2.add(jTextArea76);
        jTextArea76.setBounds(550, 150, 50, 80);

        jTextArea77.setEditable(false);
        jTextArea77.setBackground(new java.awt.Color(153, 255, 255));
        jTextArea77.setColumns(20);
        jTextArea77.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jTextArea77.setRows(5);
        jTextArea77.setText("Gestion\nempre\nsarial");
        jTextArea77.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTextArea77.setMinimumSize(new java.awt.Dimension(60, 11));
        jPanel2.add(jTextArea77);
        jTextArea77.setBounds(500, 260, 50, 80);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel8.setText("7:40 a 8:20");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(10, 70, 60, 13);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel9.setText("8:20 a 9:00");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(10, 100, 60, 13);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel10.setText("9:20 a 10:00");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(10, 150, 67, 13);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel11.setText("10:00 a 10:40");
        jPanel2.add(jLabel11);
        jLabel11.setBounds(10, 180, 74, 13);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel12.setText("10:40 a 11:20");
        jPanel2.add(jLabel12);
        jLabel12.setBounds(10, 210, 80, 13);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel13.setText("12:00 a 12:40");
        jPanel2.add(jLabel13);
        jLabel13.setBounds(10, 260, 80, 13);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel14.setText("12:40 a 1:20");
        jPanel2.add(jLabel14);
        jLabel14.setBounds(10, 290, 70, 13);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel15.setText("1:20 a 2:00");
        jPanel2.add(jLabel15);
        jLabel15.setBounds(10, 320, 60, 13);

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel16.setText("7:00 a 7:40");
        jPanel2.add(jLabel16);
        jLabel16.setBounds(10, 40, 60, 13);

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel17.setText("2:20 a 3:00");
        jPanel2.add(jLabel17);
        jLabel17.setBounds(10, 370, 60, 13);

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel18.setText("3:00 a 3:40");
        jPanel2.add(jLabel18);
        jLabel18.setBounds(10, 400, 60, 13);

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel20.setText("4:20 a 5:00");
        jPanel2.add(jLabel20);
        jLabel20.setBounds(10, 450, 60, 13);

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel19.setText("3:40 a 4:20");
        jPanel2.add(jLabel19);
        jLabel19.setBounds(10, 430, 60, 13);

        jButton1.setBackground(new java.awt.Color(153, 255, 255));
        jButton1.setText("Atras");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);
        jButton1.setBounds(0, 0, 70, 24);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 619, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 470, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Undecimo um = new Undecimo();
        um.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Lunes;
    private javax.swing.JLabel Lunes1;
    private javax.swing.JLabel Lunes2;
    private javax.swing.JLabel Lunes3;
    private javax.swing.JLabel Lunes4;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextArea jTextArea10;
    private javax.swing.JTextArea jTextArea18;
    private javax.swing.JTextArea jTextArea19;
    private javax.swing.JTextArea jTextArea20;
    private javax.swing.JTextArea jTextArea21;
    private javax.swing.JTextArea jTextArea23;
    private javax.swing.JTextArea jTextArea24;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextArea jTextArea31;
    private javax.swing.JTextArea jTextArea32;
    private javax.swing.JTextArea jTextArea33;
    private javax.swing.JTextArea jTextArea34;
    private javax.swing.JTextArea jTextArea35;
    private javax.swing.JTextArea jTextArea36;
    private javax.swing.JTextArea jTextArea39;
    private javax.swing.JTextArea jTextArea4;
    private javax.swing.JTextArea jTextArea40;
    private javax.swing.JTextArea jTextArea41;
    private javax.swing.JTextArea jTextArea42;
    private javax.swing.JTextArea jTextArea43;
    private javax.swing.JTextArea jTextArea44;
    private javax.swing.JTextArea jTextArea45;
    private javax.swing.JTextArea jTextArea46;
    private javax.swing.JTextArea jTextArea47;
    private javax.swing.JTextArea jTextArea48;
    private javax.swing.JTextArea jTextArea49;
    private javax.swing.JTextArea jTextArea50;
    private javax.swing.JTextArea jTextArea51;
    private javax.swing.JTextArea jTextArea52;
    private javax.swing.JTextArea jTextArea53;
    private javax.swing.JTextArea jTextArea54;
    private javax.swing.JTextArea jTextArea55;
    private javax.swing.JTextArea jTextArea56;
    private javax.swing.JTextArea jTextArea57;
    private javax.swing.JTextArea jTextArea58;
    private javax.swing.JTextArea jTextArea59;
    private javax.swing.JTextArea jTextArea60;
    private javax.swing.JTextArea jTextArea61;
    private javax.swing.JTextArea jTextArea62;
    private javax.swing.JTextArea jTextArea63;
    private javax.swing.JTextArea jTextArea64;
    private javax.swing.JTextArea jTextArea65;
    private javax.swing.JTextArea jTextArea66;
    private javax.swing.JTextArea jTextArea67;
    private javax.swing.JTextArea jTextArea68;
    private javax.swing.JTextArea jTextArea69;
    private javax.swing.JTextArea jTextArea7;
    private javax.swing.JTextArea jTextArea70;
    private javax.swing.JTextArea jTextArea71;
    private javax.swing.JTextArea jTextArea72;
    private javax.swing.JTextArea jTextArea73;
    private javax.swing.JTextArea jTextArea74;
    private javax.swing.JTextArea jTextArea75;
    private javax.swing.JTextArea jTextArea76;
    private javax.swing.JTextArea jTextArea77;
    private javax.swing.JTextArea jTextArea78;
    private javax.swing.JTextArea jTextArea79;
    private javax.swing.JTextArea jTextArea8;
    private javax.swing.JTextArea jTextArea80;
    private javax.swing.JTextArea jTextArea81;
    private javax.swing.JTextArea jTextArea82;
    private javax.swing.JTextArea jTextArea83;
    private javax.swing.JTextArea jTextArea84;
    private javax.swing.JTextArea jTextArea85;
    private javax.swing.JTextArea jTextArea86;
    private javax.swing.JTextArea jTextArea87;
    private javax.swing.JTextArea jTextArea88;
    private javax.swing.JTextArea jTextArea89;
    private javax.swing.JTextArea jTextArea9;
    private javax.swing.JTextArea jTextArea90;
    private javax.swing.JTextArea jTextArea91;
    private javax.swing.JTextArea jTextArea92;
    private javax.swing.JTextArea jTextArea93;
    private javax.swing.JTextArea jTextArea94;
    // End of variables declaration//GEN-END:variables
}
