/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Horarios;

/**
 *
 * @author andre
 */
public class P_Secciones extends javax.swing.JFrame {

    /**
     * Creates new form P_Secciones
     */
    public P_Secciones() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        seven1 = new javax.swing.JToggleButton();
        seven2 = new javax.swing.JToggleButton();
        seven3 = new javax.swing.JToggleButton();
        seven4 = new javax.swing.JToggleButton();
        oct1 = new javax.swing.JToggleButton();
        oct2 = new javax.swing.JToggleButton();
        oct3 = new javax.swing.JToggleButton();
        oct4 = new javax.swing.JToggleButton();
        oct5 = new javax.swing.JToggleButton();
        oct6 = new javax.swing.JToggleButton();
        nov1 = new javax.swing.JToggleButton();
        nov2 = new javax.swing.JToggleButton();
        nov3 = new javax.swing.JToggleButton();
        nov4 = new javax.swing.JToggleButton();
        nov5 = new javax.swing.JToggleButton();
        nov6 = new javax.swing.JToggleButton();
        nov7 = new javax.swing.JToggleButton();
        dec1 = new javax.swing.JToggleButton();
        dec2 = new javax.swing.JToggleButton();
        dec3 = new javax.swing.JToggleButton();
        dec4 = new javax.swing.JToggleButton();
        dec7 = new javax.swing.JToggleButton();
        dec6 = new javax.swing.JToggleButton();
        dec5 = new javax.swing.JToggleButton();
        undec1 = new javax.swing.JToggleButton();
        undec2 = new javax.swing.JToggleButton();
        undec3 = new javax.swing.JToggleButton();
        undec4 = new javax.swing.JToggleButton();
        undec7 = new javax.swing.JToggleButton();
        undec6 = new javax.swing.JToggleButton();
        undec5 = new javax.swing.JToggleButton();
        duo1 = new javax.swing.JToggleButton();
        duo2 = new javax.swing.JToggleButton();
        duo3 = new javax.swing.JToggleButton();
        duo4 = new javax.swing.JToggleButton();
        undec8 = new javax.swing.JToggleButton();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI Semilight", 1, 12)); // NOI18N
        jLabel1.setText("Sétimo");

        jLabel2.setFont(new java.awt.Font("Segoe UI Semilight", 1, 12)); // NOI18N
        jLabel2.setText("Octavo");

        jLabel3.setFont(new java.awt.Font("Segoe UI Semilight", 1, 12)); // NOI18N
        jLabel3.setText("Noveno");

        jLabel4.setFont(new java.awt.Font("Segoe UI Semilight", 1, 12)); // NOI18N
        jLabel4.setText("Décimo");

        jLabel5.setFont(new java.awt.Font("Segoe UI Semilight", 1, 12)); // NOI18N
        jLabel5.setText("Undécimo");

        jLabel6.setFont(new java.awt.Font("Segoe UI Semilight", 1, 12)); // NOI18N
        jLabel6.setText("Duodecimo");

        jButton2.setFont(new java.awt.Font("Segoe UI Semilight", 1, 12)); // NOI18N
        jButton2.setText("Atras");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        seven1.setFont(new java.awt.Font("Segoe UI Semilight", 1, 12)); // NOI18N
        seven1.setText("7-1");

        seven2.setFont(new java.awt.Font("Segoe UI Semilight", 1, 12)); // NOI18N
        seven2.setText("7-2");

        seven3.setFont(new java.awt.Font("Segoe UI Semilight", 1, 12)); // NOI18N
        seven3.setText("7-3");

        seven4.setFont(new java.awt.Font("Segoe UI Semilight", 1, 12)); // NOI18N
        seven4.setText("7-4");

        oct1.setFont(new java.awt.Font("Segoe UI Semilight", 1, 12)); // NOI18N
        oct1.setText("8-1");

        oct2.setFont(new java.awt.Font("Segoe UI Semilight", 1, 12)); // NOI18N
        oct2.setText("8-2");

        oct3.setFont(new java.awt.Font("Segoe UI Semilight", 1, 12)); // NOI18N
        oct3.setText("8-3");

        oct4.setFont(new java.awt.Font("Segoe UI Semilight", 1, 12)); // NOI18N
        oct4.setText("8-4");

        oct5.setFont(new java.awt.Font("Segoe UI Semilight", 1, 12)); // NOI18N
        oct5.setText("8-5");

        oct6.setFont(new java.awt.Font("Segoe UI Semilight", 1, 12)); // NOI18N
        oct6.setText("8-6");

        nov1.setFont(new java.awt.Font("Segoe UI Semilight", 1, 12)); // NOI18N
        nov1.setText("9-1");

        nov2.setFont(new java.awt.Font("Segoe UI Semilight", 1, 12)); // NOI18N
        nov2.setText("9-2");

        nov3.setFont(new java.awt.Font("Segoe UI Semilight", 1, 12)); // NOI18N
        nov3.setText("9-3");

        nov4.setFont(new java.awt.Font("Segoe UI Semilight", 1, 12)); // NOI18N
        nov4.setText("9-4");

        nov5.setFont(new java.awt.Font("Segoe UI Semilight", 1, 12)); // NOI18N
        nov5.setText("9-5");

        nov6.setFont(new java.awt.Font("Segoe UI Semilight", 1, 12)); // NOI18N
        nov6.setText("9-6");

        nov7.setFont(new java.awt.Font("Segoe UI Semilight", 1, 12)); // NOI18N
        nov7.setText("9-7");

        dec1.setFont(new java.awt.Font("Segoe UI Semilight", 1, 12)); // NOI18N
        dec1.setText("10-1");

        dec2.setFont(new java.awt.Font("Segoe UI Semilight", 1, 12)); // NOI18N
        dec2.setText("10-2");

        dec3.setFont(new java.awt.Font("Segoe UI Semilight", 1, 12)); // NOI18N
        dec3.setText("10-3");

        dec4.setFont(new java.awt.Font("Segoe UI Semilight", 1, 12)); // NOI18N
        dec4.setText("10-4");

        dec7.setFont(new java.awt.Font("Segoe UI Semilight", 1, 12)); // NOI18N
        dec7.setText("10-7");

        dec6.setFont(new java.awt.Font("Segoe UI Semilight", 1, 12)); // NOI18N
        dec6.setText("10-6");

        dec5.setFont(new java.awt.Font("Segoe UI Semilight", 1, 12)); // NOI18N
        dec5.setText("10-5");

        undec1.setFont(new java.awt.Font("Segoe UI Semilight", 1, 12)); // NOI18N
        undec1.setText("11-1");

        undec2.setFont(new java.awt.Font("Segoe UI Semilight", 1, 12)); // NOI18N
        undec2.setText("11-2");

        undec3.setFont(new java.awt.Font("Segoe UI Semilight", 1, 12)); // NOI18N
        undec3.setText("11-3");

        undec4.setFont(new java.awt.Font("Segoe UI Semilight", 1, 12)); // NOI18N
        undec4.setText("11-4");

        undec7.setFont(new java.awt.Font("Segoe UI Semilight", 1, 12)); // NOI18N
        undec7.setText("11-7");

        undec6.setFont(new java.awt.Font("Segoe UI Semilight", 1, 12)); // NOI18N
        undec6.setText("11-6");

        undec5.setFont(new java.awt.Font("Segoe UI Semilight", 1, 12)); // NOI18N
        undec5.setText("11-5");

        duo1.setFont(new java.awt.Font("Segoe UI Semilight", 1, 12)); // NOI18N
        duo1.setText("12-1");

        duo2.setFont(new java.awt.Font("Segoe UI Semilight", 1, 12)); // NOI18N
        duo2.setText("12-3");

        duo3.setFont(new java.awt.Font("Segoe UI Semilight", 1, 12)); // NOI18N
        duo3.setText("12-4");

        duo4.setFont(new java.awt.Font("Segoe UI Semilight", 1, 12)); // NOI18N
        duo4.setText("12-5");

        undec8.setFont(new java.awt.Font("Segoe UI Semilight", 1, 12)); // NOI18N
        undec8.setText("11-8");

        jButton1.setFont(new java.awt.Font("Segoe UI Semilight", 1, 12)); // NOI18N
        jButton1.setText("Continuar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI Semilight", 1, 12)); // NOI18N
        jLabel7.setText("Seleccione las secciones, que imparte clases y presione continuar.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(seven4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(seven3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(seven2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(seven1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(oct1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(oct2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(oct3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(oct4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(oct5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(oct6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(nov7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(nov6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(nov5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(nov4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(nov3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(nov2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(nov1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(dec7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(dec6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(dec5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(dec4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(dec3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(dec2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(dec1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(undec7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(undec6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(undec5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(undec4, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
                                .addComponent(undec3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(undec2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(undec1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(undec8))
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(duo4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(duo3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(duo2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(duo1, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 413, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jButton2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton1)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(seven1)
                            .addComponent(oct1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(oct2)
                            .addComponent(seven2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(oct3)
                            .addComponent(seven3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(oct4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(oct5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(oct6))
                            .addComponent(seven4)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nov1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nov2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nov3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nov4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nov5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nov6))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(undec1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(undec2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(undec3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(undec4))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(duo1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(duo2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(duo3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(duo4)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(undec5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(undec6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(undec7))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(dec1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dec2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dec3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dec4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dec5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dec6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(dec7)
                                    .addComponent(nov7))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(undec8)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Profesores pf = new Profesores();
        pf.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        //<editor-fold desc="Secciones" defaultstate="collapsed">
        String secciones="";
        if (seven1.isSelected()) {
            secciones+=("7-1,");
        }
        if (seven2.isSelected()) {
            secciones+=("7-2,");
        }
        if (seven3.isSelected()) {
            secciones+=("7-3,");
        }
        if (seven4.isSelected()) {
            secciones+=("7-4,");
        }
        if (oct1.isSelected()) {
            secciones+=("8-1,");
        }
        if (oct2.isSelected()) {
            secciones+=("8-2,");
        }
        if (oct3.isSelected()) {
            secciones+=("8-3,");
        }
        if (oct4.isSelected()) {
            secciones+=("8-4,");
        }
        if (oct5.isSelected()) {
            secciones+=("8-5,");
        }
        if (oct6.isSelected()) {
            secciones+=("8-6,");
        }
        if (nov1.isSelected()) {
            secciones+=("9-1,");
        }
        if (nov2.isSelected()) {
            secciones+=("9-2,");
        }
        if (nov3.isSelected()) {
            secciones+=("9-3,");
        }
        if (nov4.isSelected()) {
            secciones+=("9-4,");
        }
        if (nov5.isSelected()) {
            secciones+=("9-5,");
        }
        if (nov6.isSelected()) {
            secciones+=("9-6,");
        }
        if (nov7.isSelected()) {
            secciones+=("9-7,");
        }
        if (dec1.isSelected()) {
            secciones+=("10-1,");
        }
        if (dec2.isSelected()) {
            secciones+=("10-2,");
        }
        if (dec3.isSelected()) {
            secciones+=("10-3,");
        }
        if (dec4.isSelected()) {
            secciones+=("10-4,");
        }
        if (dec5.isSelected()) {
            secciones+=("10-5,");
        }
        if (dec6.isSelected()) {
            secciones+=("10-6,");
        }
        if (dec7.isSelected()) {
            secciones+=("10-7,");
        }
        if (undec1.isSelected()) {
            secciones+=("11-1,");
        }
        if (undec2.isSelected()) {
            secciones+=("11-2,");
        }
        if (undec3.isSelected()) {
            secciones+=("11-3,");
        }
        if (undec4.isSelected()) {
            secciones+=("11-4,");
        }
        if (undec5.isSelected()) {
            secciones+=("11-5,");
        }
        if (undec6.isSelected()) {
            secciones+=("11-6,");
        }
        if (undec7.isSelected()) {
            secciones+=("11-7,");
        }
        if (undec8.isSelected()) {
            secciones+=("11-8,");
        }
        if (duo1.isSelected()) {
            secciones+=("11-1,");
        }
        if (duo2.isSelected()) {
            secciones+=("11-2,");
        }
        if (duo3.isSelected()) {
            secciones+=("11-3,");
        }
        if (duo4.isSelected()) {
            secciones+=("11-4,");
        }
        //</editor-fold>
        
        if (!secciones.equals("")) {
            
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton dec1;
    private javax.swing.JToggleButton dec2;
    private javax.swing.JToggleButton dec3;
    private javax.swing.JToggleButton dec4;
    private javax.swing.JToggleButton dec5;
    private javax.swing.JToggleButton dec6;
    private javax.swing.JToggleButton dec7;
    private javax.swing.JToggleButton duo1;
    private javax.swing.JToggleButton duo2;
    private javax.swing.JToggleButton duo3;
    private javax.swing.JToggleButton duo4;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JToggleButton nov1;
    private javax.swing.JToggleButton nov2;
    private javax.swing.JToggleButton nov3;
    private javax.swing.JToggleButton nov4;
    private javax.swing.JToggleButton nov5;
    private javax.swing.JToggleButton nov6;
    private javax.swing.JToggleButton nov7;
    private javax.swing.JToggleButton oct1;
    private javax.swing.JToggleButton oct2;
    private javax.swing.JToggleButton oct3;
    private javax.swing.JToggleButton oct4;
    private javax.swing.JToggleButton oct5;
    private javax.swing.JToggleButton oct6;
    private javax.swing.JToggleButton seven1;
    private javax.swing.JToggleButton seven2;
    private javax.swing.JToggleButton seven3;
    private javax.swing.JToggleButton seven4;
    private javax.swing.JToggleButton undec1;
    private javax.swing.JToggleButton undec2;
    private javax.swing.JToggleButton undec3;
    private javax.swing.JToggleButton undec4;
    private javax.swing.JToggleButton undec5;
    private javax.swing.JToggleButton undec6;
    private javax.swing.JToggleButton undec7;
    private javax.swing.JToggleButton undec8;
    // End of variables declaration//GEN-END:variables
}
